### ISSUE TITLE
Add support for named exports

### ISSUE THREAD

**Issue by mrmckeb** [mrmckeb/typescript-plugin-css-modules#10]
**Is your feature request related to a problem? Please describe.**
As raised by @fmal, named exports aren't available at present.

**Describe the solution you'd like**
In theory, with the `camelCase` option, set to `"only"` (both in this plugin and CSS Loader), named exports could be created alongside or in place of the default export. This may need another option, such as `namedExports` (boolean).

**Describe alternatives you've considered**
The plugin could always export named exports for valid strings, but this would create a confusing developer experience - which is why it may need to be opt-in.

**Comment by mrmckeb** [comment]
@fmal Would the above solution be good for your needs?

**Comment by fmal** [comment]
@mrmckeb sure, your proposal of making this opt-in and effective only when `camelCase` is switched on, sounds like the best solution. Thanks for asking 😃
