### ISSUE TITLE
Support TS 4.0+

### ISSUE THREAD

**Issue by ekilah** [mrmckeb/typescript-plugin-css-modules#101]
Pretty simple, the `package.json` should support TS 4.0 which was just released. I would submit a PR to make the change, but I'm not sure what you'd prefer to use, e.g. `^3.0.0 || ^4.0.0` would work, or `>= 3.0.0`. Depends on your preferences I guess.

(TS doesn't use semantic versioning, so `3.9 -> 4.0` is no different than `3.9 -> 3.10` to them.)

**Comment by mrmckeb** [comment]
I'll make this fix today, sorry for not getting onto this sooner, I've been away.

**Comment by mrmckeb** [comment]
This is now released. Thanks again for raising this.
https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v2.5.0

**Comment by ekilah** [comment]
thanks!

**Comment by mellis481** [comment]
I'm now seeing that there is no type safety when using this library for Typescript 4.0.3. It was working previously with Typescript 3.9.7 and works when I changed the version back to that.  I'm using `typescript-plugin-css-modules@latest`.

**Comment by mrmckeb** [comment]
Hi @mellis481, are you still having this issue? I've been doing some work today and didn't have any issues with TypeScript 4.x.
