### ISSUE TITLE
typescript-eslint doesn't know about the type given from the import

### ISSUE THREAD

**Issue by krainboltgreene** [mrmckeb/typescript-plugin-css-modules#107]
The rule: https://github.com/typescript-eslint/typescript-eslint/blob/v4.8.1/packages/eslint-plugin/docs/rules/restrict-template-expressions.md

An example:
![Screen Shot 2020-11-19 at 12 10 25 AM](https://user-images.githubusercontent.com/334809/99638790-a06d9b80-29fb-11eb-9b0f-9f9099c04f1d.png)

**Comment by mrmckeb** [comment]
Hi @krainboltgreene, does your project have a `.d.ts` file as in the `README`?
https://github.com/mrmckeb/typescript-plugin-css-modules#custom-definitions

I think that will solve this issue, but let me know and I can dig further.

**Comment by krainboltgreene** [comment]
It does! And I have the relevant definitions from the README.

**Comment by mrmckeb** [comment]
Hi @krainboltgreene, sorry for the long turnaround. Unfortunately I've tried a few ways and can't reproduce this.

This works as expected:
![image](https://user-images.githubusercontent.com/5043083/105634054-e401dd00-5e64-11eb-8fce-b6ac465db37e.png)

Here I get an error as expected:
![image](https://user-images.githubusercontent.com/5043083/105634063-f1b76280-5e64-11eb-8c8a-487ce54c8408.png)

If you can provide a repro repo or more info, I can dig deeper.

**Comment by c-vetter** [comment]
I had the same problem in a vite setup and found this issue. The custom definitions as per the README didn't quite work for me due to conflicts with vite's definitions. I added `src/css-modules.d.ts` with this content:
```ts
/// <reference path="../node_modules/vite/client.d.ts" />
```

Just posting here in case someone else bumps into this.

#264 adds a note about this to the README
