### ISSUE TITLE
Problem when importing scss partials from node_modules

### ISSUE THREAD

**Issue by kyle-laracey** [mrmckeb/typescript-plugin-css-modules#111]
**Describe the bug**
When an imported SCSS stylesheet imports a partial\* like `@import '~bootstrap/scss/functions';` the node_module resolution for the file fails. This looks like an edge case of #66 and similar to #70.

\* A SCSS partial is basically a file whose basename begins with an underscore, I believe. In this case, the file's basename is actually `_functions.scss`.

**To Reproduce**
I've forked the repo used to reproduce #70. It can be found at https://github.com/kyle-laracey/typescript-plugin-css-modules-problem. Check out commit [c85152917](https://github.com/kyle-laracey/typescript-plugin-css-modules-problem/tree/c851529178fa8d9e0c07d22c4657d2dfa33385fa) ("Reproduce issue with bootstrap partial import") and reload VSCode.

**Expected behavior**
In App.tsx, I expected `styles.test` to be resolved properly to the class name defined in `test.module.scss`. Autosuggestion should work after `styles.`. Go to definition should work on `test`.

**Screenshots**
<img width="908" alt="Screen Shot 2021-01-23 at 10 16 51 PM" src="https://user-images.githubusercontent.com/1745582/105620244-ced77080-5dc8-11eb-883a-dcb2007eb3ac.png">

**Desktop (please complete the following information):**

- OS: OS X 10.14.6
- Browser chrome 
- Version 87.0.4280.88

**Other details**
As a workaround, you can fix up the `@imports` to specify the actual file names, i.e instead of `@import '~bootstrap/scss/functions';`, use `@import '~bootstrap/scss/_functions.scss';` I have done this at HEAD and you can reproduce by checking HEAD  ([9fe87322](https://github.com/kyle-laracey/typescript-plugin-css-modules-problem/tree/9fe8732262a7fc349025efd94046db05a39270b7), "fix problem") out and reloading VSCode (why you need to reload VSCode after changing the SCSS imports (as described) to get the typescript-plugin-css-modules intellisense around `styles.test` to update is unclear to me, though).

Note that these partial imports is one of the two [recommended options](https://getbootstrap.com/docs/5.0/customize/sass/#importing) for importing Bootstrap. 

The TS log contains the following:

```
Info 56   [22:29:36.531] [typescript-plugin-css-modules] Failed Error: Can't find stylesheet to import.
  ╷
1 │ @import '~bootstrap/scss/functions';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/shared.scss 1:9       @import
  src/test.module.scss 1:9  root stylesheet
Info 57   [22:29:36.539] [typescript-plugin-css-modules] Stack trace: Error: Can't find stylesheet to import.
  ╷
1 │ @import '~bootstrap/scss/functions';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/shared.scss 1:9       @import
  src/test.module.scss 1:9  root stylesheet
```

Full stacktrace at https://pastebin.com/raw/UXXkVN09.

Finally, thank you for developing this plugin, it is exactly what I was looking for.

**Comment by mrmckeb** [comment]
Hi @kyle-laracey, can you try the new version (`3.1.0`)?

The PR I just merged/released by @coreymux should have resolved this (#110).

**Comment by kyle-laracey** [comment]
Thanks, I've confirmed the issue is resolved.

**Comment by mrmckeb** [comment]
Thanks for the prompt update!
