### ISSUE TITLE
Works fine in compilation, problem with VS Code

### ISSUE THREAD

**Issue by mmanna3** [mrmckeb/typescript-plugin-css-modules#113]
The code compiles OK, but in VS Code the plugin doesn't seem to be working.

![image](https://user-images.githubusercontent.com/23342135/110272503-244a9400-7fa9-11eb-9178-ec3c26bf0523.png)

![image](https://user-images.githubusercontent.com/23342135/110272533-33c9dd00-7fa9-11eb-872c-3b362b0bd0f2.png)

As Microsoft docs said, I add the line 
`"typescript.tsdk": "node_modules\\typescript\\lib" `
in my workspace settings. Also I tried "the alternative usage" adding this
```
{
  "typescript.tsserver.pluginPaths": ["typescript-plugin-css-modules"]
}
```
to global settings.

I know that I am using the Workspace Typescript Version:
![image](https://user-images.githubusercontent.com/23342135/110377931-c1520f00-8033-11eb-974a-3a7cc33083c2.png)

It's a Create React App. 

Thanks in advance for any help.

**Comment by mmanna3** [comment]
Also, I tried downgrading the package to version 3.1.0, but the same is still happening.

**Comment by mmanna3** [comment]
I couldn't find a way to make it work. So, I uninstalled and I went for this VS Code plugin: https://github.com/clinyong/vscode-css-modules. Sorry for the link, but maybe it helps someone. Thanks anyway.

**Comment by mrmckeb** [comment]
Hi @mmanna3, this works with Create React App today - we use that project for testing.

If you could share a reproduction in a git repo, I can take a look at it and help to solve :)

**Comment by mmanna3** [comment]
Hi!

This is the repo:
https://github.com/mmanna3/BlueServant/tree/typescript-plugin-css-modules

I created a branch named "typescript-plugin-css-modules" and each one of the three last commits are for configuration.

The code is in the "Frontend" folder.

Thanks a lot!

**Comment by mrmckeb** [comment]
Hi @mmanna3, it looks like this issue is related to this:
https://github.com/mrmckeb/typescript-plugin-css-modules/issues/24

Basically, we don't have native support for basePath, as it's not supported by default in Sass. You just need to change to the below in your `tsconfig.json` and that should be all :)

```
"plugins": [
      {
        "name": "typescript-plugin-css-modules",
        "options": {
          "rendererOptions": {
            "sass": {
              "includePaths": ["src"]
            }
          }
        }
      }
    ],
```

**Comment by mmanna3** [comment]
It works! Thank you!

Yes, I think it would be great if at least this information was in the readme. If it was the default behaviour for Sass, even better.
