### ISSUE TITLE
Files compile fine, but VSCode doesn't autocomplete and shows errors

### ISSUE THREAD

**Issue by laoqiu233** [mrmckeb/typescript-plugin-css-modules#114]
**Describe the bug**
I'm using LESS as a preprocessor, I've added an import in a file like this `@import (reference) '../base.module.less'` (also tried without reference tag), and the auto-completion for the classes in this file is gone. 
I've read #113 and it still doesn't solve my problem, since the person who created the issue is using sass and I'm using less.

**To Reproduce**
I'm not really sure how this happened, I just added the line to import and the IntelliSense is gone! I've uploaded the code to a temporary repo so maybe someone could read the code and find out what's wrong with it.
https://github.com/laoqiu233/for_issue

**Expected behavior**
VSCode should provide IntelliSense and not throw errors.

**Screenshots**
![The LESS file with the line](https://user-images.githubusercontent.com/25715854/112259870-bf837f00-8cb4-11eb-9213-3b50ef71410e.png)
*The LESS file with the line*

![An empty style object, but the code compiles and works fine](https://user-images.githubusercontent.com/25715854/112259817-a1b61a00-8cb4-11eb-9d4a-f9ad1f3f6c1e.png)
*An empty style object, but the code compiles and works fine*

![VSCode complains and shows errors](https://user-images.githubusercontent.com/25715854/112259850-b397bd00-8cb4-11eb-928a-de3a98ae584f.png)
*VSCode complains and shows errors*

![Commented out the line](https://user-images.githubusercontent.com/25715854/112259996-e772e280-8cb4-11eb-896f-eb1659aff580.png)
*Commented out the line*

![Works fine after deleting the line](https://user-images.githubusercontent.com/25715854/112259906-cd390480-8cb4-11eb-950d-d02969206d82.png)
*Works fine after deleting the line*

**Desktop (please complete the following information):**

- OS: Windows 10 64bit
- Browser: Chrome
- Version 89.0.4389.90

**Comment by wingsico** [comment]
same problems. need helps...

**Comment by mrmckeb** [comment]
Thanks for the reproduction, @laoqiu233 - it really helped! And, sorry for the very slow reply.

This is a known issue with Less, which can be resolved by adding `(css)`:
```diff
- @import url('https://fonts.googleapis.com/css2?family=Monoton&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;1,100;1,200;1,300;1,400;1,500&display=swap');
+ @import (css) url('https://fonts.googleapis.com/css2?family=Monoton&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;1,100;1,200;1,300;1,400;1,500&display=swap');
```

I found the issue here:
https://github.com/less/less.js/issues/3188

I hope that helps!

@wingsico if you still have an issue, please raise a new issue with a small reproduction and I'll take a look ASAP :)

**Comment by wingsico** [comment]
> Thanks for the reproduction, @laoqiu233 - it really helped! And, sorry for the very slow reply.
> 
> This is a known issue with Less, which can be resolved by adding `(css)`:
> 
> ```diff
> - @import url('https://fonts.googleapis.com/css2?family=Monoton&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;1,100;1,200;1,300;1,400;1,500&display=swap');
> + @import (css) url('https://fonts.googleapis.com/css2?family=Monoton&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;1,100;1,200;1,300;1,400;1,500&display=swap');
> ```
> 
> I found the issue here for reference: [less/less.js#3188](https://github.com/less/less.js/issues/3188)
> 
> I hope that helps!
> 
> @wingsico if you still have an issue, please raise a new issue with a small reproduction and I'll take a look ASAP :)

Ok, the same problems still exist. I will raise a new issue for it.

**Comment by mrmckeb** [comment]
Thanks @wingsico. This was definitely the fix for the reproduction in this issue, I tested multiple times. When you raise an issue, I can help sort out your issue too!

**Comment by wingsico** [comment]
> Thanks @wingsico. This was definitely the fix for the reproduction in this issue, I tested multiple times. When you raise an issue, I can help sort out your issue too!

A new issue raised here. #122
