### ISSUE TITLE
Intellisense in VS Code not working/erroring

### ISSUE THREAD

**Issue by mellis481** [mrmckeb/typescript-plugin-css-modules#116]
Here is how I've set up `typescript-plugin-css-modules` (version 3.2.0) in my non-CRA project:

```
// tsconfig.json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "jsx": "react",
    "jsxFactory": "h",
    "lib": ["dom", "es5", "scripthost", "es2015", "es2015.promise", "es2016.array.include"],
    "module": "commonjs",
    "target": "es5",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noImplicitThis": true,
    "plugins": [
      {
        "name": "typescript-plugin-css-modules",
        "options": {
          "classnameTransform": "camelCase"
        }
      }
    ],
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strictBindCallApply": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true
  },
  "exclude": ["node_modules", "build", "cypress"]
}
```

```
// src/types/styles/css-modules.d.ts
declare module '*.module.css' {
  const classes: { [key: string]: string };
  export default classes;
}

declare module '*.module.scss' {
  const classes: { [key: string]: string };
  export default classes;
}

declare module '*.module.sass' {
  const classes: { [key: string]: string };
  export default classes;
}
```

```
// src/components/my-component.tsx
import styles from './my-component.module.scss';

export const MyComponent: FunctionalComponent<{ }> = (props) => {
    return (
     <>
        <h1 className={styles.appTitle}>Foo</h1>
        <h1 className={styles.asdfasdf}>Bar</h1>
      </>
    );
};

```

```
// src/components/my-component.module.scss
.app-title {
  font-size: 20px;
  line-height: 32px;
}
```

In `MyComponent`, styles are correctly applied for the first `h1`, but:
1. There is no Intellisense to indicate valid classes to use for the `styles` module.
2. It does not error on the second `h1` with the bad class (`styles.asdfasdf`).

Any idea why this isn't working?  It seems like I have everything set up correctly based on the README.

**Comment by mellis481** [comment]
Oh weird, so I'm using Typescript 4.2.3.  I thought I'd see what happened when I switched to 3.9.9 and now `typescript-plugin-css-modules` works as expected.  I'm now finding a comment I added to this ticket in the past about this same issue that I apparently failed to follow up on (I have some pretty serious Github Outlook files for work :)): https://github.com/mrmckeb/typescript-plugin-css-modules/issues/101.

So are you saying you're not having this issue with TS 4+?

**Comment by ichengde** [comment]
```
    "typescript": "^4.2.4",
    "typescript-plugin-css-modules": "^3.2.0",
```

I used the plug-in smoothly. I have solved some minor problems. If you encounter problems, you can check the log. There is a detailed output in the log; open tsserver.log;
There are several key points:
1. Remember to choose the TypeScript version of workspace;
2. Remember to check the plugin options in the plugin, such as customMatcher and rendererOptions;

It is good if you switch to the old version,you can see if the location of the load plugin is correct;

**Comment by mrmckeb** [comment]
I can confirm this works for in my testing with TS4 as well, if it's OK we'll close this off and reopen if more issues arise?

@ichengde let me know if there's more we can do to improve documentation here :)
