### ISSUE TITLE
Add less file extension to default matcher

### ISSUE THREAD

**Issue by Aqours** [mrmckeb/typescript-plugin-css-modules#12]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add less file extension(.less) to default matcher. I think less is as popular as sass/scss.
```
"\\.module\\.(sa|sc|le|c)ss$"
```

**Describe alternatives you've considered**

**Additional context**

**Comment by mrmckeb** [comment]
@Aqours Is there a reason that the `customMatcher` isn't working for you? Support for using that in VSCode should come in the next release (very close now).

If it's something that people really want, we could look to add that - but as @xiaoxiangmoe said, this plugin is designed to align with `create-react-app` in terms of the default settings - but is definitely not only for CRA.

**Comment by mrmckeb** [comment]
@Aqours I was just discussing this with a colleague. I'm open to this change - but want to be cautious.

I propose as an option, would it be OK to have something like this?
```"extendedMatchers": true```

Which might look like `"\\.module\\.(sa|sc|le|pc|c)ss$"` or even `"\\.(sa|sc|le|pc|c)ss$"`?

**Comment by ifmos** [comment]
> @Aqours I was just discussing this with a colleague. I'm open to this change - but want to be cautious.
> 
> I propose as an option, would it be OK to have something like this?
> `"extendedMatchers": true`
> 
> Which might look like `"\\.module\\.(sa|sc|le|pc|c)ss$"` or even `"\\.(sa|sc|le|pc|c)ss$"`?

Thanks for this great plugin!  I think supporting less will be really nice and help more people

**Comment by mrmckeb** [comment]
Closed by #20. Will be released later today :)
