### ISSUE TITLE
Option to disable named export

### ISSUE THREAD

**Issue by Monchi** [mrmckeb/typescript-plugin-css-modules#120]
**Is your feature request related to a problem? Please describe.**

Named export that was added via #22 is great. But sometimes the class name conflicts with the component name and disturbs auto-completion.

**Describe the solution you'd like**

Add option to disable named export so the class name wouldn't be shown in auto-completion.

**Describe alternatives you've considered**

No idea.

**Additional context**

It will be similar to css-loader's `namedExport` option. [(doc)](https://github.com/webpack-contrib/css-loader#namedexport)

**Comment by Monchi** [comment]
I can work on this if it sounds good.

**Comment by mrmckeb** [comment]
I had originally planned to make this opt-in, and should have - but for now I've added a flag which defaults to `true`. This will be in the next release.

**Comment by Monchi** [comment]
Great, Thanks!

**Comment by mrmckeb** [comment]
This is now released as v3.3.0.
https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v3.3.0
