### ISSUE TITLE
Type derivation fails when using less variables.

### ISSUE THREAD

**Issue by wingsico** [mrmckeb/typescript-plugin-css-modules#122]
**Describe the bug**
Type derivation fails when using less variables.

**To Reproduce**

1. Install dependencies & prepare the tsconfig & declare type & use workspace's ts version.
![image](https://user-images.githubusercontent.com/26498668/117239959-5de13380-ae62-11eb-967d-e0afe16c18cc.png)
![image](https://user-images.githubusercontent.com/26498668/117239984-69ccf580-ae62-11eb-9a65-903dfbc78bc7.png)

2. create index.ts & create index.module.less & fill style without less variables.
![image](https://user-images.githubusercontent.com/26498668/117240791-3723fc80-ae64-11eb-8a57-9c9a1a12998b.png)
![image](https://user-images.githubusercontent.com/26498668/117240196-e65fd400-ae62-11eb-9331-440ac7c5e243.png)
*Now it works well*

3. Add less variables to the less file.
![image](https://user-images.githubusercontent.com/26498668/117240372-3fc80300-ae63-11eb-8a29-de548b64d996.png)

![image](https://user-images.githubusercontent.com/26498668/117240381-43f42080-ae63-11eb-8b9d-3cb0c09e58ca.png)

**Expected behavior**
When I use less variables, it should be work well too.

**Screenshots**
See ** To Reproduce **

**Desktop (please complete the following information):**

- OS: [e.g. iOS]: MacOS
- Browser [e.g. chrome, safari]: Chrome
- Version [e.g. 22]: 90.0.4430.93

**Additional context**
These less variables are injected through less-loader.

**Comment by SageWu** [comment]
same issue

**Comment by mrmckeb** [comment]
Hi @wingsico, are you able to supply a small reproduction of this issue for me?

**Comment by wingsico** [comment]
> Hi @wingsico, thanks for raising this issue. Are you able to supply a small reproduction of this issue for me?

@mrmckeb 

Ok, here is the reproduction link: https://github.com/wingsico/typescript-plugin-css-modules-issue

Focus on the `src/App.tsx` and `src/App.m.less`

**Comment by kintz09** [comment]
I believe I'm experiencing a very similar issue. My project is based on CRA v4, using scss files, and CRACO to fix [this bug](https://github.com/facebook/create-react-app/pull/10511#issuecomment-834273898) with sass exports.

The project compiles just fine like the OP's example, and I get the same empty object for the imported stylesheet.
Module declarations are handled by CRA in this project.

### Style Object Broken
<details>
  <summary>Style Object Broken</summary>

Here's the plugin configuration:
![image](https://user-images.githubusercontent.com/10118752/119050243-6ebb9a00-b976-11eb-8edd-f6b3d602f014.png)

Here's the SCSS file:
![image](https://user-images.githubusercontent.com/10118752/119050002-200e0000-b976-11eb-8ee8-fe901475b1fd.png)

Here's the the TSX file showing the empty style object:
![image](https://user-images.githubusercontent.com/10118752/119050167-53508f00-b976-11eb-8e2f-883d5e9d819e.png)

</details>

### Style Object Working
<details>
  <summary>Style Object Working</summary>

Here's the modified SCSS file not using the import:
![image](https://user-images.githubusercontent.com/10118752/119050917-5a2bd180-b977-11eb-8d2f-cdd61aa7c2d0.png)

Here's the same TSX file showing the working style object:
![image](https://user-images.githubusercontent.com/10118752/119050989-70399200-b977-11eb-90a3-926154405478.png)
</details>
 

If you'd like me to put together a reproduction environment, just let me know and I'll do my best.

**Comment by wingsico** [comment]
> I believe I'm experiencing a very similar issue. My project is based on CRA v4, using scss files, and CRACO to fix [this bug](https://github.com/facebook/create-react-app/pull/10511#issuecomment-834273898) with sass exports.
> 
> The project compiles just fine like the OP's example, and I get the same empty object for the imported stylesheet.
> Module declarations are handled by CRA in this project.
> 
> ### Style Object Broken
> Style Object Broken
> Here's the plugin configuration:
> ![image](https://user-images.githubusercontent.com/10118752/119050243-6ebb9a00-b976-11eb-8edd-f6b3d602f014.png)
> 
> Here's the SCSS file:
> ![image](https://user-images.githubusercontent.com/10118752/119050002-200e0000-b976-11eb-8ee8-fe901475b1fd.png)
> 
> Here's the the TSX file showing the empty style object:
> ![image](https://user-images.githubusercontent.com/10118752/119050167-53508f00-b976-11eb-8e2f-883d5e9d819e.png)
> 
> ### Style Object Working
> Style Object Working
> Here's the modified SCSS file not using the import:
> ![image](https://user-images.githubusercontent.com/10118752/119050917-5a2bd180-b977-11eb-8d2f-cdd61aa7c2d0.png)
> 
> Here's the same TSX file showing the working style object:
> ![image](https://user-images.githubusercontent.com/10118752/119050989-70399200-b977-11eb-90a3-926154405478.png)
> 
> If you'd like me to put together a reproduction environment, just let me know and I'll do my best.

The bug about importing is similar to this #114 . You can try for it.

**Comment by kintz09** [comment]
@wingsico Thank you for pointing me in the right direction! I was able to resolve my issue by reading through issue #114, #113, and #24.

I hadn't realized my import path was non-standard.

I was able to fix the issue just by changing the path but also through this plugin's options:

1.  Changing the import statement in the SCSS file to a relative path fixed the issue:
```
// PlayerInit.module.scss
// @import "Player/Lib/vlp-ui/sass/materialAnimation";
@import "../../../Lib/vlp-ui/sass/materialAnimation";
...
```
2. Leaving the import as is but changing the plugin's options in tsconfig.json also fixed the issue:
```
// tsconfig.json
{
  "compilerOptions": {
    ...
    "baseUrl": "src",
    "plugins": [
      {
        "name": "typescript-plugin-css-modules",
        "options": {
          "classnameTransform": "camelCaseOnly",
          "rendererOptions": {
            "sass": {
              "includePaths": ["src"]
            }
          }
        }
      }
    ]
  },
  "include": ["src"]
}
```

Thanks again for your quick support!

**Comment by mrmckeb** [comment]
Thanks for this @wingsico, I think I've found the issue.

This fails:
```less
.App {
  color: @blue;
}
```

This works:
```less
@blue: rgb(0, 0, 255);

.App {
  color: @blue;
}
```

This is because the less rendered doesn't automatically pick up global variables, it processes each file independently.

There are a few solutions:
1. Import files with variables whenever you use them.
1. Define the variables in the `tsconfig.json` - but that's obviously a very bad solution, and not scalable.
1. We can try to add a feature to this plugin to find/import these variables.

An example of the second option (again, I don't recommend this)
```json
    "plugins": [
      {
        "name": "typescript-plugin-css-modules",
        "options": {
          "rendererOptions": {
            "less": {
              "globalVars": {
                "blue": "rgb(0, 0, 255)"
              }
            }
          }
        }
      }
    ]
```

What do you think would be a nice solution here for you?

I think option 3 is possible, we could possibly automatically append `@import "[variable-file-1].less"; @import "[variable-file-2].less";` to the top of each file... you would just need to provide the relative paths.

**Comment by wingsico** [comment]
> Thanks for this @wingsico, I think I've found the issue.
> 
> This fails:
> 
> ```css-less
> .App {
>   color: @blue;
> }
> ```
> 
> This works:
> 
> ```css-less
> @blue: rgb(0, 0, 255);
> 
> .App {
>   color: @blue;
> }
> ```
> 
> This is because the less rendered doesn't automatically pick up global variables, it processes each file independently.
> 
> There are a few solutions:
> 
> 1. Import files with variables whenever you use them.
> 2. Define the variables in the `tsconfig.json` - but that's obviously a very bad solution, and not scalable.
> 3. We can try to add a feature to this plugin to find/import these variables.
> 
> An example of the second option (again, I don't recommend this)
> 
> ```json
>     "plugins": [
>       {
>         "name": "typescript-plugin-css-modules",
>         "options": {
>           "rendererOptions": {
>             "less": {
>               "globalVars": {
>                 "blue": "rgb(0, 0, 255)"
>               }
>             }
>           }
>         }
>       }
>     ]
> ```
> 
> What do you think would be a nice solution here for you?
> 
> I think option 3 is possible, we could possibly automatically append `@import "[variable-file-1].less"; @import "[variable-file-2].less";` to the top of each file... you would just need to provide the relative paths.

Thanks for your reply @mrmckeb .

Actually, the option 2 is suit for me. But I think the plugin can ignore this kind of problem, so that the type can be displayed normally.

**Comment by mrmckeb** [comment]
OK, thanks for the update @wingsico. I looked, and unfortunately I don't see an option in Less to build with errors. So if a variable can't be found, classname generation will fail.

If you're happy with that solution for now, can we close this issue? Or did I misunderstand?

**Comment by wingsico** [comment]
> OK, thanks for the update @wingsico. I looked, and unfortunately I don't see an option in Less to build with errors. So if a variable can't be found, classname generation will fail.
> 
> If you're happy with that solution for now, can we close this issue? Or did I misunderstand?

@mrmckeb OK, I will close it soon. Thanks for your help. :)

**Comment by Carnia** [comment]
> This is because the less rendered doesn't automatically pick up global variables, it processes each file independently.
> 
> There are a few solutions:
> 
> 1. Import files with variables whenever you use them.
> 2. Define the variables in the `tsconfig.json` - but that's obviously a very bad solution, and not scalable.
> 3. We can try to add a feature to this plugin to find/import these variables.

> What do you think would be a nice solution here for you?
> 
> I think option 3 is possible, we could possibly automatically append `@import "[variable-file-1].less"; @import "[variable-file-2].less";` to the top of each file... you would just need to provide the relative paths.

@mrmckeb 
I think option3 is what I am looking for.
In my project, i used a webpack loader called `style-resources-loader`, its option looks like that:
```js
{
    loader: "style-resources-loader",
    options: {
        patterns: path.resolve(__dirname, "../src/common/global-style/*.less"),
    },
},
``` 
its desciption:
>This loader is a CSS processor resources loader for webpack, which injects your style resources (e.g. variables, mixins) into multiple imported css, sass, scss, less, stylus modules.
  It's mainly used to:
  share your variables, mixins, functions across all style files, so you don't need to @import them manually.
override variables in style files provided by other libraries (e.g. ant-design) and customize your own theme.

In this development environment, i will use global variables in many less files（without`@import "***.less"`），so I think  Option 3 is the best。

**Comment by cat-walk** [comment]
> OK, thanks for the update @wingsico. I looked, and unfortunately I don't see an option in Less to build with errors. So if a variable can't be found, classname generation will fail.
> 
> If you're happy with that solution for now, can we close this issue? Or did I misunderstand?

Hey, is there any progress with this problem? I think many less user suffer from this.
