### ISSUE TITLE
Report error with VS Code

### ISSUE THREAD

**Issue by lqh-1997** [mrmckeb/typescript-plugin-css-modules#126]
**Describe the bug**
Same as issue #113 , but I already added the following config in `tsconfig.json`
![image](https://user-images.githubusercontent.com/32805893/119073503-0aedab80-ba20-11eb-9b55-466599d04ae2.png)
If I change scss path to relative path, the VScode will work as expected

**To Reproduce**
https://github.com/lqh-1997/-typescript-plugin-css-modules-issue

**Expected behavior**

**Screenshots**
Error type: has no property 'test'
![image](https://user-images.githubusercontent.com/32805893/119073626-3f616780-ba20-11eb-8f54-9d24e8a27daa.png)
![image](https://user-images.githubusercontent.com/32805893/119073662-4d16ed00-ba20-11eb-8cf6-702f4d8771fc.png)

**Desktop (please complete the following information):**

- OS: window10
- Browser chrome
- Version 90

**Additional context**

**Comment by mrmckeb** [comment]
Hi @lqh-1997, thanks for raising this.

It looks like this is just a configuration issue - you need to wrap "rendererOptions" in an "options" object.
See: https://github.com/mrmckeb/typescript-plugin-css-modules#options

It should look like this when fixed :)
```json
    "plugins": [
      {
        "name": "typescript-plugin-css-modules",
        "options": {
          "rendererOptions": {
            "sass": {
              "includePaths": ["src/assets/scss"]
            }
          }
        }
      }
    ]
```

Please let me know if you have any more issues!
