### ISSUE TITLE
Absolute imports not functioning (Am I doing it wrong?)

### ISSUE THREAD

**Issue by benjamin-andersen** [mrmckeb/typescript-plugin-css-modules#134]
**Describe the bug**
When I try to use an absolute import in a scss module, VSCode complains that the class types don't exist.

**To Reproduce**

1. Create a global scss file
2. Create an scss module file in a different directory
3. Import the global scss file in the other scss file
4. Import the scss module and use it in a component

**Expected behavior**
No errors.

**Notes**
- works fine with relative imports
- my imports are correct, the files exist

**Screenshots**
![image](https://user-images.githubusercontent.com/70706530/121420243-af795400-c921-11eb-994b-2040514e1962.png)
![image](https://user-images.githubusercontent.com/70706530/121420333-ca4bc880-c921-11eb-947e-4b016a25c1ef.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 91.0.4472.77

**Comment by mrmckeb** [comment]
Hi @benjamin-andersen, have you tried without the leading slash, as`@import 'src/common/scss/config'`? 
![image](https://user-images.githubusercontent.com/5043083/121774073-f6b54e00-cb88-11eb-97a4-5e38b3fb8146.png)

If that doesn't work, are you able to supply a small reproduction? Perhaps with Create React App?

**Comment by benjamin-andersen** [comment]
Aha I feel dumb now, but thanks for the clarification :). Removing the extra `/` in front of `/src/common/scss/config` fixes it.

I have a follow-up question though:

I tried making an alias for `styles/config` --> `src/common/scss/config` by adding this line to my `tsconfig.json`:

```json
{
  "paths": {"styles/*": ["common/scss/*"]},
  "plugins": [{"name": "typescript-plugin-css-modules"}]
}
```

But I assume there is a setting I have to change for the plugin to get this to work because that doesn't seem to do it.

**Comment by mrmckeb** [comment]
Hi @benjamin-andersen, yes you can look at the Sass options in [renderer options](https://github.com/mrmckeb/typescript-plugin-css-modules#rendereroptions), and pass through paths there :)

Unfortunately everyone does CSS modules differently, so there is often a little configuration needed on the user side... I wish I could do it all auto-magically!

**Comment by benjamin-andersen** [comment]
Thanks!
