### ISSUE TITLE
Help Creating React Components from CSS Modules?

### ISSUE THREAD

**Issue by egucciar** [mrmckeb/typescript-plugin-css-modules#135]
**Is your feature request related to a problem? Please describe.**

Hello! I was wondering what would be the best way to augment CSS modules to leverage the powerful `customTemplate` you guys provided in conjunction with the following idea:

Lets say we have the desire to create something like this:
```js
export default function Cta({ label, link }) {
  return (
    <CtaContainer test>
      <a className="uds-button" rel="noreferrer" href={link} target="_blank">
        {label}
        <div className="uds-ml-1">
          <LinkOut />
        </div>
      </a>
    </CtaContainer>
  );
}
```

from something like this:

```css
.CtaContainer {
  @media (--medium-viewport) {
    max-width: 243px;
    margin: 0 auto;
  }
}

.test {
  border: 3px solid red;
}
```

I think its great (and it works!) but, i would like TS support for this! in my understanding the best experience would likely be to just add it as a extension to this plugin some how. Let me know what you think!

Here is the transform:

```js
import classes from './index.module.css';

function getFilteredClasses(filtered) {
  const filteredProps = Object.keys(filtered);
  const filteredClasses = Object.entries(classes).reduce(
    (acc, [prop, className]) => ({
      ...acc,
      [className]: filteredProps.includes(prop),
    }),
    {}
  );
  return filteredClasses;
}
const { CtaContainer } = Object.entries(classes).reduce(
  (acc, [ComponentName, componentClass]) => ({
    ...acc,
    // eslint-disable-next-line react/display-name
    [ComponentName]: ({ children, className, ...props }) => (
      <div
        className={classNames(
          componentClass,
          getFilteredClasses(props),
          className
        )}
      >
        {children}
      </div>
    ),
  }),
  {}
) as any;
```

**Comment by egucciar** [comment]
My thinking is I'll need to apply the transform some how with babel to produce the components for runtime use, I'm new to this kinda stuff but i think this idea has some merit. Any pointers would be useful! I'd like especially to test something out locally.

**Comment by mrmckeb** [comment]
Hi @egucciar, unfortunately this isn't possible with TypeScript today. As developers, we can provide types through TypeScript plugins, but nothing more. Even then the types are ignored during build time, which is quite limiting.

Here are the docs on that:
https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin#whats-a-language-service-plugin

You may want to look at something like [`ttypescript`](https://www.npmjs.com/package/ttypescript) which supports "transforms". I know there's a small community around that. You can also build your own TypeScript wrapper to do something similar, although I haven't tried that myself.

I hope that helps! I wish I could do more, but again, this is a TypeScript limitation.
