### ISSUE TITLE
Use sass module in vue3 by it: Property '' does not exist on type '{}'.

### ISSUE THREAD

**Issue by ghost** [mrmckeb/typescript-plugin-css-modules#138]
import var scss in vs.config.js
//vue.config.js

```
module.exports = {
  css: {
    requireModuleExtension: true,
    loaderOptions: {
      scss: {
        prependData: `
                      @import "@/style/gobal.scss";
                  `,
      },
    },
  },
}
```
![image](https://user-images.githubusercontent.com/75852065/122358953-b9d1c880-cf87-11eb-9aea-20961c383292.png)
![image](https://user-images.githubusercontent.com/75852065/122359079-d40ba680-cf87-11eb-9cb6-d2cdb23faefc.png)
if delete the var, it's working fine.

**Comment by this-ren** [comment]
I has this error too

**Comment by mrmckeb** [comment]
Hi there, this is likely because the variables aren't available. You can look at the Sass options ([here](https://github.com/mrmckeb/typescript-plugin-css-modules#rendereroptions)).

Unfortunately, if you don't import the vars you're using, there's no way this plugin can know they exist. 

In your build process, this is probably handled by Webpack and the loader for Sass, which is why it seems to work magically :)

**Comment by Dodje** [comment]
@mrmckeb
Didn't want to create an issue, I hope it's okay if I ask it here whether it is possible to make it work with typescript vue files?

I've found a message about module not working with files except [js/ts](https://github.com/mrmckeb/typescript-plugin-css-modules/issues/94#issuecomment-661619319)

It work fine with .tsx files for me, but I need it working with vue..

**Comment by mrmckeb** [comment]
Hi @Dodje, please do raise an issue and we can talk there!

I'm definitely OK with expanding support, that comment was actually about VSCode's command palette. Right now, it should work anywhere the TypeScript compiler works... so I'll be interested to understand more.

**Comment by mrmckeb** [comment]
I just noticed that the original post had a typo which may have been the cause ` @import "@/style/gobal.scss";` - where `gobal` should be `global`.
