### ISSUE TITLE
class names are not transformed to camelCase

### ISSUE THREAD

**Issue by 3hson** [mrmckeb/typescript-plugin-css-modules#139]
**Describe the bug**
I'm using cra typescript template with typescript-plugin-css-modules and set classnameTransform": "camelCase" but class names are not transformed.

**To Reproduce**
here is the [sandbox](https://codesandbox.io/s/great-bose-zb3j7?file=/tsconfig.json)

**Expected behavior**
expect to transform .App-header to appHeader

**Comment by laoqiu233** [comment]
Same problem, hope to get an answer soon!

**Comment by mrmckeb** [comment]
Hi there, I've just tested this repo and it works for me - but not in CodeSandbox, as I think they don't load TS plugins.

Are you using VSCode, and if so, did you follow the instructions?
- https://github.com/mrmckeb/typescript-plugin-css-modules#visual-studio-code

Here's an example of what I see with your repro locally :)

![image](https://user-images.githubusercontent.com/5043083/127825870-7125a263-3053-48ef-a358-2bf10fd1e4cd.png)

**Comment by 3hson** [comment]
the exported types in VSCode are fine but when i start the project the classes in the generated css are not in camelCase.

no style as you see

![Screenshot from 2021-08-02 14-13-09](https://user-images.githubusercontent.com/36244081/127841213-062fc9d1-d103-4387-9369-97e32f614766.png)

**Comment by chungweileong94** [comment]
This plugin only handles the TypeScript types. As for runtime, you will need to change the `localsConvention` on the CSS loader.

**Comment by mrmckeb** [comment]
Thanks @chungweileong94! I'll close this off.

**Comment by ShikinChen** [comment]
in react-scripts 5.0.1, generated css are not in camelCase,but webstorm provides camelCase suggestions
