### ISSUE TITLE
Nested SCSS selectors

### ISSUE THREAD

**Issue by ChristianIvicevic** [mrmckeb/typescript-plugin-css-modules#14]
**Is your feature request related to a problem? Please describe.**
Although the usage of CSS Modules in CRA apps makes scoping class names almost obsolete I was considering to use SCSS nesting in a particular case, but noticed that the plugin doesn't resolve those classes at all. A sample in BEM notation looks as follows:

    .container {
        width: 100vw;
        height: 100vh;

        &--half {
            width: 50vw;
        }

        &--third {
            width: 33vw;
        }
    }

The plugin unfortunately only creates types for `container` but completely ignores there are `container--half` and `container--third` available as well.

**Describe the solution you'd like**
It would be nice to have the feature added, that the plugin supports nested SCSS classes as described.

**Describe alternatives you've considered**
This is not a pressing issue since the use of nested classes is arguably unnecessary with CSS Modules anyways and I was basically considering them to remove the amount of classes used in various components with the very same name. The latter makes searching for those names slightly more annoying.

**Comment by mrmckeb** [comment]
Thanks for reporting this, I'll definitely be looking at this in the next release - I think there's an underlying issue with the util used to analyse the CSS file.

Sorry for the delay, I've been on holiday (it's that time of the year) and will be looking at this over the coming days ;)

**Comment by mrmckeb** [comment]
Resolved, thanks for your patience @ChristianIvicevic!
