### ISSUE TITLE
Is it possible to query this plugin's results via a custom script (for CI)?

### ISSUE THREAD

**Issue by ekilah** [mrmckeb/typescript-plugin-css-modules#140]
**Is your feature request related to a problem? Please describe.**
I would like to have a CI rule that prevents JS from being merged that refers to classnames that don't exist.

**Describe the solution you'd like**
I'm hoping for a programmatic way to call/ask/query this plugin for its errors, so I can read them and fail CI if there are any.

**Describe alternatives you've considered**
I haven't tried anything, mostly wondering if this is possible already. I'm not familiar with TS's plugin architecture. 

**Additional context**
I know that we can't get normal compiler errors from your README note: https://github.com/mrmckeb/typescript-plugin-css-modules/tree/82ba03548c3d2193508e1a4dbc47c1aa9b22943c#about-this-plugin

**Comment by mrmckeb** [comment]
Hi @ekilah, unfortunately TypeScript doesn't allow this today - TypeScript doesn't support plugins during build/compile, only in the IDE (sadly).

There are tools that generate `.d.ts` files for each CSS file, which you could look to use in the CI. Maybe that would work for you?

**Comment by ekilah** [comment]
What are those tools, I'm curious?

I know that TS doesn't support plugins during the build/compile process, but I was wondering if we could somehow talk to the language service/whatever _does_ interact with this plugin via our own script/something that isn't an IDE. I know this is out of scope for your project here, but I'm hoping to learn more on this front to maybe build something that could do this. 

Any ideas/help you have would be appreciated!

**Comment by mrmckeb** [comment]
Hi @ekilah, sorry for the slow reply. I there are a number of CSS module Webpack plugins to do this, along with command line tools like `typed-css-modules`.
