### ISSUE TITLE
Error when using math.div.（Property 'xxxxx' does not exist on type '{}'.）

### ISSUE THREAD

**Issue by hiseri** [mrmckeb/typescript-plugin-css-modules#142]
**Describe the bug**
An error occurs when importing a file using `sass:math`.
（`Property 'xxxxx' does not exist on type '{}'.`）

**Screenshots**
<img width="619" src="https://user-images.githubusercontent.com/8216721/128844905-8a335a07-c906-446e-8e09-e37ad2f444d8.png">

**To Reproduce**
* sample.tsx
```tsx
import React from 'react';
import css from './sample.module.scss';

export const Sample: React.FC = () => {
    return <div className={css.sampleClass}>sample code</div>;
};
```

* sample.module.scss
```scss
@use "sass:math";

.sampleClass {
    margin-right: math.div(100, 2);
}
```

**Comment**
sass@1.33.0 recommends using math.div instead of /.
https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1330
```
Deprecate the use of / for division. The new math.div() function should be used instead
```

`mrmckeb/typescript-plugin-css-modules` uses sass@1.32.13.
https://github.com/mrmckeb/typescript-plugin-css-modules/blob/main/package.json#L81

I specified sass@1.33.0 as a test and the error was resolved.
```
// package.json
  "resolutions": {
    "sass": "1.33.0"
  },
```

I kindly ask for your confirmation.

**Comment by mrmckeb** [comment]
Hi @hiseri, this might require a Sass upgrade then! 

I'll take a look ASAP :)

**Comment by ScorpAL** [comment]
Friendly reminder :)

**Comment by mrmckeb** [comment]
This is now done - sorry that it took so long.

I'll release in the next few hours.
