### ISSUE TITLE
cannot work when setting baseUrl

### ISSUE THREAD

**Issue by www159** [mrmckeb/typescript-plugin-css-modules#145]
**Describe the bug**
when setting `baseUrl` and `path` to resolve alias, the plugin cannot recongnize class name.

**To Reproduce**
1. tsconfig.json
![image](https://user-images.githubusercontent.com/40891547/137715649-5cf043aa-7796-4b51-a692-0030160a35d9.png)
2. when using
![image](https://user-images.githubusercontent.com/40891547/137715921-170eb083-bc86-4e84-b07f-dda044dfd21e.png)
3. no intellsense
![image](https://user-images.githubusercontent.com/40891547/137716170-4709cc66-9892-4fd5-8459-2ed635a94a52.png)

**some version**
![image](https://user-images.githubusercontent.com/40891547/137716342-c3bda975-4c75-4fed-8e8c-0cb399f58c8d.png)
and ts is 4.4.3

**Comment by mrmckeb** [comment]
Hi @www159, are you able to provide a reproduction? I can then take a look for you. Sorry for the slow response, I've been moving countries.

**Comment by mrmckeb** [comment]
Closing this off as we have tested with `baseUrl` and it works. Without a reproduction we can't go further, sorry!
