### ISSUE TITLE
Tailwind Just-In-Time Important Modifier Breaks Class Name Parsing

### ISSUE THREAD

**Issue by doug-shontz** [mrmckeb/typescript-plugin-css-modules#148]
**Describe the bug**
Tailwind important notation breaks parsing logic.

**To Reproduce**
We are using SASS (scss version) and Tailwind together within typescript and are using this module to export our class names into our TSX files (React).

Use the SCSS file below and note specifically the Tailwind syntax of !important (i.e. sm:!w-1/2).  If we leave in the important symbol for Tailwind, our TSX file shows no class names when imported.  Using a standard syntax like

```typescript
import styles from "./my.module.css
```

we can see that styles.registration (from the example below) does not exist...in fact...none of them exist.  BUT, if we take out all of the Tailwind important notations of built-in important modifier (https://tailwindcss.com/docs/just-in-time-mode#built-in-important-modifier), the code again then shows all class names correctly.

When you hover over the class name the error you get is "Property 'registration' does not exist on type '{}'.ts(2339)"

This is specific to the Just-In-Time mode to Tailwind, so the problem IS very specific to Tailwind and using SASS nesting.

**Expected behavior**
Class names would still be exported correctly.

**Test Code**
We intentionally took this from an existing app and made it a bit more verbose than necessary to illustrate the problem

```css
.registration {
   @apply flex flex-col w-full py-4 mb-8 max-w-4xl;

   &Header {
      &Question {
         @apply mt-4;

         &Note {
            @apply italic -mt-1 mb-2;
         }
      }
   }

   &Body {
      @apply flex flex-row;

      &Answer {
         @apply absolute text-primary rounded-full w-8;

         &Group {
            @apply flex flex-row items-center mr-4 cursor-pointer;
         }

         &Checked {
            @apply flex justify-center items-center rounded-full w-8 h-8 mr-2 bg-white;
         }

         &Unchecked {
            @apply rounded-full mr-2 bg-white border-2 border-gray-600 h-8 w-8;
         }

         &Text {
            @apply select-none;
         }
      }
   }

   &Count {
      @apply flex flex-col w-full;

      &Header {
         @apply mt-6;
      }

      &View {
         @apply flex flex-row w-full justify-start items-center;

         &Input {
            @apply flex w-full py-2 font-light text-sm focus:outline-none text-left border-gray border-l border-r border-t-0 border-b-0 focus:shadow-none focus:ring-0;

            &View {
               @apply flex flex-row w-full xs:w-3/4 sm:!w-1/2 md:!w-1/3 mt-2 justify-start items-center bg-gray-0 rounded-lg border border-gray;
            }

            &Button {
               @apply flex justify-center items-center h-full p-2;

               &Icon {
                  @apply text-primary p-2 h-full w-8 cursor-pointer;
               }
            }
         }
      }
   }
}
```

**Desktop (please complete the following information):**

- OS: MacOS Big Sur (11.6
- Visual Studio Code (1.62.1)

**Comment by mrmckeb** [comment]
Hi @doug-shontz, are you able to provide a reproduction repo? I can then take a look!
