### ISSUE TITLE
Can I use it in jsx？

### ISSUE THREAD

**Issue by whale2002** [mrmckeb/typescript-plugin-css-modules#170]
We use nextjt to develop.
I want to use it in jsx, but it seems that it does not work in jsx. And it is normal in tsx.
How can it use it in jsx? @mrmckeb 
<img width="884" alt="image" src="https://user-images.githubusercontent.com/79465534/201049635-678669ba-f043-451e-8d8b-4785c56e416d.png">
<img width="930" alt="image" src="https://user-images.githubusercontent.com/79465534/201049769-ea6815ba-0553-4379-b663-29d97e0f6a9e.png">

**Comment by kanapka94** [comment]
`jsx` is JavaScript file so TypeScript will not work. Look at screen:

<img width="928" alt="obraz" src="https://user-images.githubusercontent.com/7600593/201545673-571b9bc3-c1c4-41fd-9270-60eb5f6bfbee.png">

Change `.jsx` to `.tsx`

**Comment by mrmckeb** [comment]
This will 100% work in `.tsx`, but as @kanapka94 said, I'm not sure TypeScript will even run the plugin for JavaScript files. Our design focus is TypeScript.
