### ISSUE TITLE
"Go to definition" and "rename" do not work properly

### ISSUE THREAD

**Issue by OliverJAsh** [mrmckeb/typescript-plugin-css-modules#175]
**Describe the bug**
"Go to definition" and "rename" do not work properly

**To Reproduce**

1. Open a TS file
2. "Go to definition" on a class name, or try to rename it using "rename symbol"

**Expected behavior**
The operation is successful.

**Screenshots**

The CSS file is opened/changed but in the wrong location.

https://user-images.githubusercontent.com/921609/204132679-d4b01ac8-eb5b-47d3-adcc-6a9cfd066ac4.mov

**Comment by mrmckeb** [comment]
This hasn't been released yet, sorry! It should be today.

**Comment by musjj** [comment]
It's still broken. The definition jump for `*.scss` files seems also complete wrong on my end. Can this issue be re-opened?

**Comment by mrmckeb** [comment]
Hi @musjj, can you please open a new issue with a reproduction?

Rename won't work, but go to definition partially works.
