### ISSUE TITLE
LESS files containing nested function are failing

### ISSUE THREAD

**Issue by erwan-joly** [mrmckeb/typescript-plugin-css-modules#18]
**Describe the bug**
LESS files containing function are failing to "build"

**To Reproduce**
Create a Less files with a function like 
```
.my-header-to-show {
}

.header() {
    > .failed {
        .another-function('blue');
    }
}
```

then mouseover the styles in your import.

**Comment by mrmckeb** [comment]
Sorry for the *very* slow reply @erwan-joly. I'll be looking into this over the weekend and plan to release a new build then.

The extension was only really tested with Sass, and Less support was always going to be limited - but I understand the need to support this.
