### ISSUE TITLE
should i use typescript-plugin-css-modules if i use CRA?

### ISSUE THREAD

**Issue by jr-developer1** [mrmckeb/typescript-plugin-css-modules#186]
Hello! in my project i use create-react-app --typescript + sass. 
So I can use import styles as an object (import styles from '/styles.module.scss ';) and use them (<div className={styles.root} />).  And i can use hints in my IDE.
Can you please tell me what your package is for? Maybe i should not use yours package, if i use CRA?
thanks!

**Comment by jr-developer1** [comment]
please tell me the cases in which I need typescript-plugin-css-modules in CRA?

**Comment by dongyuwei** [comment]
If you use css modules.

**Comment by mrmckeb** [comment]
You don't have to use this plugin, but it will provide autocomplete on CSS module import, and also warnings/errors in your IDE when classes are imported that don't exist in the CSS module.

Please let me know if you have any other questions!
