### ISSUE TITLE
LESS mixins are not suported

### ISSUE THREAD

**Issue by spawluk** [mrmckeb/typescript-plugin-css-modules#19]
**Describe the bug**
When using mixins, styles properties are not built.

**To Reproduce**
```
.box-sizing(@sizing) {
  box-sizing: @sizing;
  -webkit-box-sizing: @sizing;
  -moz-box-sizing: @sizing;
  -ms-box-sizing: @sizing;
}

.someClass {
  .box-sizing(content-box);
}
```

```
import styles from "./Styles.less";
...
<input className="someClass"/>
```

**Expected behavior**
Generate correct output on import

**Screenshots**
![image](https://user-images.githubusercontent.com/3480057/57915296-be9b8e00-7890-11e9-802b-ad937dc10285.png)

**Comment by mrmckeb** [comment]
Thanks for this issue @spawluk. So, right now this extension supports only the most basic features of Sass/Less - that is, classes and nesting. Sorry for the inconvenience...

I'm working on updating this now, and will hopefully have a new version out shortly with full support.

Please feel free to submit a PR if you have suggestions in the meantime :)
