### ISSUE TITLE
Enabling goToDefinition removes kebab-case outputs

### ISSUE THREAD

**Issue by mariusGundersen** [mrmckeb/typescript-plugin-css-modules#191]
If you enable goToDefinition then the kebab-case styles cannot be used

This is because it uses only the class names that matches the filter, here: https://github.com/mrmckeb/typescript-plugin-css-modules/blob/main/src/helpers/createDtsExports.ts#L69

The result is that all kebab-case classes are filtered out

**Comment by mrmckeb** [comment]
Thanks for reporting this. I'll need to investigate further - this was working, but may have been broken.

I'm currently refactoring this fairly heavily and will add some tests around it.

**Comment by mrmckeb** [comment]
Hi @mariusGundersen, I'm getting back to this after a holiday sorry. To be clear, it sounds like you're using classname transforms and want to support the original and transformed classnames?

**Comment by mariusGundersen** [comment]
Yes, the camelCase transform. But even if you choose the kebab-case transform it will cause problems. The problem is that it needs to be an export on a line in the file, and kebab-case isn't a valid variable name and therefore can't be exported (if I remember correctly, it's been a while since I looked into it)

**Comment by mrmckeb** [comment]
I might need to do a large refactor for TypeScript 5.0, and if that's the case, I can look at this alongside that work.

I'll add this to the 4.3 milestone, which is where TS 5.0 support is.

**Comment by mrmckeb** [comment]
This should now be resolved in `v4.2.3`, please let me know if you still hit this issue after upgrading.

**Comment by mrmckeb** [comment]
If you're feeling a little adventurous, this fix is also in [`v5.0.0-beta.0`](https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v5.0.0-beta.0), which has TypeScript 5.x support and I'd love to have more people test that version out.
