### ISSUE TITLE
TypeScript 5.0 support

### ISSUE THREAD

**Issue by Sheraff** [mrmckeb/typescript-plugin-css-modules#196]
**Describe the bug**
Upgrading to TS version 5.0.0-beta this extension seems to break. So I know this is a beta version but it's the proper time to adjust libraries so they're compatible on launch.

Here's `styles`'s type under v5:
```ts
(alias) const styles: {
    readonly [key: string]: string;
}
import styles
```

**To Reproduce**
I have a globals.d.ts with only
```ts
declare module "*.module.css"
```
My tsconfig is nothing out of the ordinary (pasted below) but here's the important bit
```json
    "plugins": [
      { "name": "typescript-plugin-css-modules" }
    ]
```
And of course, vscode's config contains
```json
"typescript.tsdk": "node_modules/typescript/lib",
```
And package.json
```json
"typescript-plugin-css-modules": "^4.1.1",
```

**Expected behavior**
Changing nothing but the TS version is what breaks the types. I'd love to have it working like under TS v4.9.5. Here's what *the exact same `styles`* is typed as under TS 4:
```ts
(alias) let styles: {
    'like-slide': string;
    'like-jump': string;
    'dislike-slide': string;
    'dislike-fall': string;
    'reset-slide': string;
    'reset-clip-right': string;
    'reset-clip-left': string;
    ... 33 more ...;
    offline: string;
}
import styles
```

**tsconfig**
```json
{
  "compilerOptions": {
    "baseUrl": "./src",
    "target": "ESNext",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "noUncheckedIndexedAccess": true,
    "plugins": [
      { "name": "typescript-plugin-css-modules" }
    ]
  },
  "include": [
    "next-env.d.ts",
    "next-auth.d.ts",
    "**/*.ts",
    "**/*.tsx",
    "**/*.js",
    "globals.d.ts"
  ],
  "exclude": ["node_modules"]
}
```

**Comment by mrmckeb** [comment]
Hi @Sheraff, thanks for reporting this. I'll take a look soon.

I'm just finalising a refactor with a lot of fixes, and after that I'll prioritise this issue.

**Comment by mrmckeb** [comment]
I've been digging into this, and it looks like a bit of a rewrite.

The TLDR is that there have been several breaking API changes on the TypeScript side. When this plugin was authored, it was OK to override TS internal methods, which now throws.

I won't ship it this weekend, but will try to find time ASAP - as I know TS 5.0 is very close to release.

**Comment by mrmckeb** [comment]
I'm working on this at the moment, after hours. Making some progress, I hope I can release a beta next weekend.

**Comment by Sheraff** [comment]
This is great news, thanks a lot!

**Comment by mrmckeb** [comment]
This is now available in the latest beta. Please let me know how it goes:
https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v5.0.0-beta.0

**Comment by Sheraff** [comment]
> Please let me know of any issues you hit. I'll create a stable release once I've had some feedback.

It seems to be working great! Thanks a ton for doing this work.

There is just a slight issue but that's probably because we're in the world of beta releases: during `npm i` there was an issue with resolving the dependencies.

```
While resolving: my-repo-name@0.1.0
npm ERR! Found: typescript@5.0.1-rc
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"5.0.1-rc" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@">=4.0.0" from typescript-plugin-css-modules@5.0.0-beta.0
```

This can be "fixed" (or more accurately "bypassed") by doing a `npm i --force`

**Comment by mrmckeb** [comment]
Thank you! I think that'll be an easy enough fix. When 5.x is out, it'll pass with `>=4`, but I think the `-rc` versions need to be listed.

**Comment by andelkocvjetkovic** [comment]
Hello, after I updated to TS 5.0 and this plugins to v5.0.0-beta.0 autocomplete for paths doesn't work. I use Nvim with LSP.

**Comment by Sheraff** [comment]
> Hello, after I updated to TS 5.0 and this plugins to v5.0.0-beta.0 autocomplete for paths doesn't work. I use Nvim with LSP.

@andelkocvjetkovic  Which exact version of typescript are you using? I had `typescript@5.0.1-rc` and it worked fine.

**Comment by jakebailey** [comment]
The effect of #211 was that the 5.0 RC was effectively partially bundled with the plugin; #213 fixed this but hasn't been released. It's possible that things aren't working due to that mismatch.

**Comment by mrmckeb** [comment]
As it seems to be working for most people - with the only noted issues seemingly related to the issue @jakebailey spotted - I think I'll move forward and release this.

**Comment by mrmckeb** [comment]
This should be shipped! Please let me know how it goes, I haven't had time to thoroughly test - but wanted to get this into more hands. This version ships with @jakebailey's fix.
https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v5.0.0

**Comment by andelkocvjetkovic** [comment]
Hey, I switched to 5.0.0 version. I still have the same problem. Everything works for relative paths, but when I used alias it is broken.

**Comment by Sheraff** [comment]
I tried this new release with TS 5.0.2. It works fine for me with absolute imports. I don't have aliases in the codebase I use for these tests, but all the imports are "absolute from the baseUrl" and the tsconfig defines the base url

```json
"compilerOptions": {
  "baseUrl": "./src",
```

**Comment by andelkocvjetkovic** [comment]
which editor do you use ?

**Comment by Sheraff** [comment]
> which editor do you use ?

I'm on VSCode not Nvim sorry

**Comment by Sheraff** [comment]
> I just tried with VSCode same issue.

Do you have VSCode using the typescript version you installed (instead of the one that it ships with)? (not sure if the same would apply to Nvim) That would be in your vscode settings:
```json
"typescript.tsdk": "node_modules/typescript/lib"
```

**Comment by mrmckeb** [comment]
Did it work for you before v5 and TypeScript 5 @andelkocvjetkovic?

**Comment by andelkocvjetkovic** [comment]
Yes, it works with alias in 
    "typescript": "4.8.4",
    "typescript-plugin-css-modules": "4.2.3",

<img width="601" alt="Screenshot 2023-03-23 at 09 02 26" src="https://user-images.githubusercontent.com/56834937/227140159-d2c47b54-2053-4b72-a118-1d8bf6e2c2ce.png">

**Comment by andrei-datcu** [comment]
I'm also experiencing the behavior @andelkocvjetkovic reported: alias imports are not working with ts 5.0.

Note that it's the import statement from the ts code that breaks the plugin. Importing with alias from scss code still works.

**Comment by Ghirigoro** [comment]
@mrmckeb FWIW I also am experiencing essentially the same issue as @andelkocvjetkovic (although it's not with scss - just regular css module). I can't say if the issue was happening before since I started using the plugin after the release of TS 5.
