### ISSUE TITLE
alternative to postcss-icss-selectors that is using an outdated generic-names dependency

### ISSUE THREAD

**Issue by GZLiew** [mrmckeb/typescript-plugin-css-modules#198]
**Describe the bug**
Hi we are getting a bunch of security issue due to the dependency of this plugin using 
a outdated version of generic-names

```
typescript-plugin-css-modules@4.1.1 requires loader-utils@^0.2.16 via a transitive dependency on generic-names@1.0.3
```

**Expected behavior**
should not have vulnerability issue

**Comment by mrmckeb** [comment]
This is now available in `v4.2.1`:
- https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v4.2.1
- https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v4.2.0
