### ISSUE TITLE
Usage with yarn workspaces

### ISSUE THREAD

**Issue by qrohlf** [mrmckeb/typescript-plugin-css-modules#200]
I'm working within a monorepo that is using yarn v3 workspaces, and I'm running into issues with getting typescript-plugin-css-modules to work correctly.

By looking at the TS server logs, I was able to determine that the following SCSS was causing typescript-plugin-css-modules to throw "cannot find module" errors when the following file was within a css file in the `monorepo/libs/some-nested-workspace` dir:

```scss
@use '@company/ui/global-styles/variables';

.clubPageHeader {
  text-transform: uppercase;
  font-size: 13px;
}
```

Digging a bit deeper, this was happening because the `monorepo/libs/some-nested-workspace/node_modules` directory did not contain the `@company/ui` package. The `@company/ui` package was being hoisted to the top level `monorepo/node_modules` directory, since multiple workspaces depended on it.

I was able to implement a hacky fix for this using the following strategy:

<img width="578" alt="Screenshot 2023-02-13 at 11 33 12 AM" src="https://user-images.githubusercontent.com/347189/218557329-bd4efc37-6227-4e01-b6de-c3423d18b8be.png">

However, this is obviously fragile and less than ideal, since it only supports a hard-coded level of nesting, and (depending on the level of nesting of the compiled page), might result in typescript-plugin-css-modules looking _too far_ up, and going outside of the monorepo to look for files which could result in some really weird unexpected behavior in certain situations.

I am curious if you have any suggestions for a solution here? Because the `tsconfig` file has to be JSON, I don't think I can specify a [custom importer](https://sass-lang.com/documentation/js-api/interfaces/Options#importers), which would be my first choice for a strategy to fix the issue.

**Comment by mrmckeb** [comment]
Hi @qrohlf, I'd love to dig into this a little more. Are you able to create a small reproduction repo?

There may be some quality-of-life tweaks we can make so that you don't need to define config like this.

**Comment by qrohlf** [comment]
@mrmckeb sure, I can do that! Normally I'd try to include a repro case from the start but since it's kind of a PITA to set up a multi-package typescript monorepo I figured I'd see if there was an easy solution I was missing before going down that path.

I should be able to have a repro for this by Monday or Tuesday.

**Comment by mrmckeb** [comment]
No problem, I understand. Obviously the issues that get raised with something like this can be pretty hairy, which is why I sometimes ask for a full repro.

**Comment by mrmckeb** [comment]
I'll close this off for now, but please reopen if this is still an issue.
