### ISSUE TITLE
Can it be used on neovim？

### ISSUE THREAD

**Issue by horaoen** [mrmckeb/typescript-plugin-css-modules#206]

**Comment by mrmckeb** [comment]
Hi @horaoen, if it supports the TypeScript Language Service, then yes!

From what I can see, it does:
https://terminalroot.com/how-to-configure-lsp-for-typescript-in-neovim/

**Comment by horaoen** [comment]
> Hi @horaoen, if it supports the TypeScript Language Service, then yes!
> 
> From what I can see, it does: https://terminalroot.com/how-to-configure-lsp-for-typescript-in-neovim/

thanks a lot

**Comment by horaoen** [comment]
I installed typescript language server, but typescript language server does not have css module related functions, then I installed cssmodules-language-server, it works very well, anyway the purpose is achieved

**Comment by mrmckeb** [comment]
Thanks for the update @horaoen - you would need to install the TypeScript Language Server and configure it to use your `tsconfig.json` and this plugin I think, but I couldn't say for sure without testing it... I'm glad you found a working solution!

**Comment by horaoen** [comment]
Thank you for your reply @mrmckeb, it works after configing the tsconfig.json.

**Comment by johhnsmmith198** [comment]
@horaoen How did you configure typescript-language-server to use your local tsconfig.json, please?

**Comment by horaoen** [comment]
> @horaoen How did you configure typescript-language-server to use your local tsconfig.json, please?

just fellow the readme and put config `{
  "compilerOptions": {
    "plugins": [{ "name": "typescript-plugin-css-modules" }]
  }
}` into tsconfig.json. I think tssersver would automatic reading tsconfig.json which is in your front-end project.

**Comment by nyngwang** [comment]
@mrmckeb Don't worry, I just confirmed that your plugin works well with neovim. If there is a problem is only possible culprit will be tsconfig.json. This is because neovim just uses tsserver behind the scenes and it reads tsconfig.json.
