### ISSUE TITLE
Classes with composes break the exports (for the plugin)

### ISSUE THREAD

**Issue by calvellido** [mrmckeb/typescript-plugin-css-modules#207]
### Description

CSS Modules files with any class that include the `composes` keyword break the export for that file, in the context of the plugin. As noted, not only the class that include that keyword doesn't seem visible to the plugin, but any on the same file too. The three types of possible origin for the `composes` setting: from the same file, other files, or global classes produce the same result of an empty object `{}` as the object exported.

The `composes` keyword is defined in the CSS Modules spec in:

https://github.com/css-modules/css-modules#dependencies

It's also supported through Webpack's CSS Loader in:

https://webpack.js.org/loaders/css-loader/#composing

---

_The project builds the classes including these composed classes correctly and as expected through the use of the webpack loader and config._

---

### To Reproduce

Steps to reproduce the behaviour:

1. Define a CSS Modules file, e.g: `index.module.css`
2. Set the composes keyword in one of its classes, e.g: `cardContainer`
3. Import the CSS Module file on a TS file, e.g: `import styles from './index.module.css';`
4. Use any of the classes exported by the CSS Module, e.g: `textContainer`
5. `Property 'textContainer' does not exist on type '{}'.ts(2339)`

### Expected behaviour
Classes should still be understood as exported as usual, whether some of them include the `composes` keyword or not.

### Screenshots

Error with composes:
![image](https://user-images.githubusercontent.com/7753447/222508340-81cc9477-3f41-4631-a5b3-5e471c4f5f85.png)
![image](https://user-images.githubusercontent.com/7753447/222508502-84d18d83-aa3c-4eee-9e51-85bcbadf1dc3.png)

Usual behaviour:
![image](https://user-images.githubusercontent.com/7753447/222508762-c0f0a6c9-99ec-430c-a8c2-583570fa7eb6.png)
![image](https://user-images.githubusercontent.com/7753447/222508829-b274a7be-b6c5-4537-86b1-7cb08ea02c72.png)

### Desktop

- OS: GNU/Linux, Linux Mint 21.1 Cinnamon
- Editor: VS Code 1.75.1
- Browser: Not applicable

**Comment by mrmckeb** [comment]
Hi there, thanks for raising this! I'm guessing most people don't use this feature, as this is the first report we've had.

I think it'll be an easy fix though. We'll need to add one or two of these plugins:
https://github.com/webpack-contrib/css-loader/blob/master/src/utils.js#L776-L779

I'll try to get this done and shipped in the next few days!

**Comment by calvellido** [comment]
Yes, there's not a lot of `composes` mentions in general in the net, as I think it's probably far from being the main CSS Modules concept that people are using them for. But, nonetheless, I think it's an interesting feature that could be very usable depending on the project.

Even better if it's not a very hard task to add to the plugin.

Thanks for having a look!

**Comment by shayded-exe** [comment]
Seconding the need for this to be fixed. Just started using the plugin and immediately ran into this issue.

Glad to hear it'll be fixed soon!

**Comment by mrmckeb** [comment]
This should now be resolved in [`v4.2.3`](https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v4.2.3), please let me know if you still hit this issue after upgrading.

Again, sorry this happened. I think this may have worked up until a very recent refactor, where some internals were swapped out due to deprecations.

**Comment by mrmckeb** [comment]
If you're feeling a little adventurous, this fix is also in [`v5.0.0-beta.0`](https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v5.0.0-beta.0), which has TypeScript 5.x support and I'd love to have more people test that version out.

**Comment by calvellido** [comment]
Awesome, many thanks @mrmckeb!  Will report back if I am able to branch out the project to test it under TypeScript 5

**Comment by strlns** [comment]
Great work! 🚀
 
Came here from searching the issues, first thought fix in 4.2.3 wasn't working after restarting VSCode + TS language server after updating.
Then after reinstalling again, clearing npm cache and fully restarting VSCode, everything worked like a charm again.

Thank you!
