### ISSUE TITLE
Not working in `.svelte` files

### ISSUE THREAD

**Issue by aradalvand** [mrmckeb/typescript-plugin-css-modules#212]
Following [this comment](https://github.com/mrmckeb/typescript-plugin-css-modules/issues/187#issuecomment-1464858571).

I'm using [SvelteKit](https://kit.svelte.dev/) (which is based on Vite) along with [Vite's CSS Module capability](https://vitejs.dev/guide/features.html#css-modules), in case that's relevant. I'm also using the official [VS Code extension for Svelte](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode).

When importing `*.module.scss` files in `.ts` files, the imported variable is typed properly, meanwhile in `.svelte` files, it's not.

**Comment by mrmckeb** [comment]
Hi @aradalvand, sorry I've been slow at getting back to this. Are you able to set up a simple reproduction? I can then dig in and try to make this work.

**Comment by mrmckeb** [comment]
Closing this off as we need a repro to dig deeper.
