### ISSUE TITLE
Incorrect type when using Yarn workspace

### ISSUE THREAD

**Issue by VlasenkoStanislav** [mrmckeb/typescript-plugin-css-modules#214]
**Describe the bug**
I'm trying to set up a Yarn workspace, but I'm randomly getting `{}` type on import in one or all packages.

**To Reproduce**
[Reproduction Github Repo](https://github.com/VlasenkoStanislav/typescript-plugin-css-modules-issue)

**Expected behavior**
Types should be correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/62524253/225075974-501e9094-8e3a-4b4a-aecd-94fc8ed6ad1b.png)

**Desktop (please complete the following information):**
- OS: Windows 11
- Editor: VSCode: 1.76.1

**Comment by KornelijusGlinskas** [comment]
I'm getting this error as well with the same yarn workspace setup.

**Comment by mrmckeb** [comment]
Hi @VlasenkoStanislav, unfortunately when I opened that project locally and installed with Yarn (1.22), it worked. I then opened both workspaces and was able to reproduce the error in this project.

We made multiple changes to the plugin recently, so I tried upgrading to v5 and it seems to have fixed the issue - which I think is good news. Can you confirm?
<img width="435" alt="image" src="https://user-images.githubusercontent.com/5043083/230858241-0120841e-ee54-4c40-81ef-364cd68822ef.png">

**Comment by VlasenkoStanislav** [comment]
Hi @mrmckeb, yes, upgrading to v5 fixed the issue! 🎉
