### ISSUE TITLE
When importing a non-existent index.module.less file, ts will crash.

### ISSUE THREAD

**Issue by eightHundreds** [mrmckeb/typescript-plugin-css-modules#216]
**Describe the bug**

When importing a non-existent index.module.less file, ts will crash.

The problematic import is in a third-party package (node_module).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by OrangeTimes** [comment]
same issues with sass

**Comment by mrmckeb** [comment]
The fix for this has been released as [5.0.1](https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v5.0.1).
