### ISSUE TITLE
Add a configuration option to exclude paths 

### ISSUE THREAD

**Issue by adam-26** [mrmckeb/typescript-plugin-css-modules#219]
**Is your feature request related to a problem? Please describe.**
This plugin includes the `node_modules` folder in the search path.
Some packages are published that include CSS imports (ie:`import './some.css' )` but the `.css` file is not included in the package, that causes this plugin to crash.

**Describe the solution you'd like**
Add a configuration option `excludePath(s)`, that accepts a `string | RegEx` that is then used to exclude the specified paths from reading css files.

**Describe alternatives you've considered**
None.

**Additional context**
Being able to exclude paths would likely improve plugin performance.

**Comment by mrmckeb** [comment]
Hi @adam-26, the "crash" issue should have been solved by #218 (thank you). Do you think that's enough for now?

The plugin itself only tries to read CSS from `node_modules` if it's imported (or imported by an import).

**Comment by adam-26** [comment]
Hi @mrmckeb, thanks for fixing and merging #218 it's much appreciated. I agree that that's enough for now, thanks again.
