### ISSUE TITLE
Add support for CSS in JS libraries like Astroturf and Linaria

### ISSUE THREAD

**Issue by jpmaga** [mrmckeb/typescript-plugin-css-modules#220]
**Is your feature request related to a problem? Please describe.**
The type safety is great, but it is a shame we can't use it for specific css tags, like linaria's `css` or astroturf's `css` and `stylesheet`, probably the latter one would be the easiest to implement, since you write exactly the same as you would in a css module.

**Describe the solution you'd like**
In the options one could define the tags that the plugin would then parse as if it was a .module.[c|sc|le|...]ss file.

```ts
const styles = stylesheet`
.root {
  color: red;
}
`

console.log(styles.root) // no error
console.log(styles.something) // Property 'something' does not exist on type ....
```

**Describe alternatives you've considered**
Define the object as something like this, but feels much less ergonomic, and you lose the ability to nest classes (at least in a simple way):
```ts
const styles = {
root: css`color: red;`,
another_class: css`color: blue;`
}
```

**Comment by mrmckeb** [comment]
Hi @jpmaga, I've seen extensions that validate template literals before, like this - so it is definitely possible.
- https://github.com/styled-components/typescript-styled-plugin

Is this something you'd be interested in contributing to? I can see why it would be useful.

**Comment by mrmckeb** [comment]
As this is out of scope for now, I'll close this one off. But still open to this if anyone wants to contribute.
