### ISSUE TITLE
typescript-plugin-css-modules not work with scss features

### ISSUE THREAD

**Issue by TikkY-hash** [mrmckeb/typescript-plugin-css-modules#221]
I download your plugin, and have some problems if I try use it with scss features
![image](https://user-images.githubusercontent.com/52102787/229453017-56b83bd9-8f09-412f-a78b-0be8a2791a10.png)

**Comment by mrmckeb** [comment]
Hi @TikkY-hash, are you able to share more information? The plugin does work with SCSS - we have tests for that - but there may be something specific to your case.

Did you also follow the instructions in the README?
https://github.com/mrmckeb/typescript-plugin-css-modules#installation

I'd be happy to help out more if you can provide a small reproduction repo :)

**Comment by reintroducing** [comment]
What @xobotyi is describing seems to be similar to my issue: https://github.com/mrmckeb/typescript-plugin-css-modules/issues/224

it appears that using external modules in a file (aka non local project mixins that may come from node_modules rather than imports from local to the project file system files) are breaking the type hinting and showing TS errors.

as for the original comment on this issue, I can also confirm that other than what I described above, this plug-in works great with Sass.

**Comment by TikkY-hash** [comment]
I have this problem, only if i try use media queries with a css variables
<img width="1440" alt="Снимок экрана 2023-05-17 в 18 29 31" src="https://github.com/mrmc
<img width="1440" alt="Снимок экрана 2023-05-17 в 18 29 40" src="https://github.com/mrmckeb/typescript-plugin-css-modules/assets/52102787/706eed4b-995a-4b5f-8fde-2beaff6a2f53">
<img width="1440" alt="Снимок экрана 2023-05-17 в 18 31 26" src="https://github.com/mrmckeb/typescript-plugin-css-modules/assets/52102787/704971f7-0711-4d30-b553-76d67a8f3bab">
<img width="1440" alt="Снимок экрана 2023-05-17 в 18 31 33" src="https://github.com/mrmckeb/typescript-plugin-css-modules/assets/52102787/964eee59-7c0a-42cb-8431-fde952823e6a">

keb/typescript-plugin-css-modules/assets/52102787/d23652bf-c5ea-4e11-b976-516e7f1b55c4">

**Comment by LeoCaprile** [comment]
Having the same issue as @TikkY-hash, if the scss module contains any type of media queries, the plugin stop working

**Comment by LeoCaprile** [comment]
I did some research on the code provided by @TikkY-hash, looks like he have a syntax error on his media query thats why the plugin dont transform correctly:

![image](https://github.com/mrmckeb/typescript-plugin-css-modules/assets/71847541/172dbd87-b76e-4360-ae8d-a12d4de33ac0)

following the code provided by @TikkY-hash 

![image](https://github.com/mrmckeb/typescript-plugin-css-modules/assets/71847541/a1b67da6-9350-45d8-bb87-cced0bce46e4)

here's some media queries examples in scss, using variables:

```scss
$small: 300px;
$medium: 900px;

.smth {
  //some CSS
  @media screen and (max-width: $small) {
    //do Smth
  }
  @media screen and (min-width: $medium) {
    //do Smth
  }
}

```

**Comment by yslpn** [comment]
If I use the @use directive, the plugin refuses to work. Is there any news in this direction?

`Property 'betaFlag' does not exist on type '{}'.ts(2339)`

<img width="616" alt="image" src="https://github.com/mrmckeb/typescript-plugin-css-modules/assets/14806611/4783ab7b-1c47-43bc-9cf7-3cdf0f3cb934">
<img width="616" alt="image" src="https://github.com/mrmckeb/typescript-plugin-css-modules/assets/14806611/d9cc6b8e-3a31-47e4-8ac7-9884b20fea41">

**Comment by mrmckeb** [comment]
Hi @yslpn, are you able to provide a minimal reproduction?

Even if it's just a new Next.js project (or your preferred framework) set up to demonstrate the failure, that will help me to track down the issue.

**Comment by islami00** [comment]
If you're having issues with `@import` not working in vscode for path aliases, it was added in #105 . To make it work you need to:

1. Ensure the file you're importing is a scss module. (i.e ends in .module)
2. Import as (`@alias/filename.module`)


### References
1. fixture with the imports: https://github.com/mrmckeb/typescript-plugin-css-modules/blob/80d13619d338462de6430495306e88f1444af5d4/src/helpers/__tests__/fixtures/tsconfig-paths.module.scss
2. Test with the path definition:  https://github.com/mrmckeb/typescript-plugin-css-modules/blob/80d13619d338462de6430495306e88f1444af5d4/src/helpers/__tests__/getDtsSnapshot.test.ts#L213

**Comment by mrmckeb** [comment]
Hi @murm, you'll need to configure this plugin the same way. You should be able to use `additionalData` as explained in the README for this plugin:
https://github.com/mrmckeb/typescript-plugin-css-modules?tab=readme-ov-file#options

**Comment by mrmckeb** [comment]
We've had a contribution from @rmachado-studocu that should improve how we handle aliases, which hopefully resolves the remaining issues here:
https://github.com/mrmckeb/typescript-plugin-css-modules/pull/251

I've added a test today to confirm that `@use` is working as expected:
https://github.com/mrmckeb/typescript-plugin-css-modules/pull/258

If you're still experience issues after this release, I ask that you raise a new issue with a reproduction repo to help us to dig deeper - thanks!

**Comment by murm** [comment]
> Hi @murm, you'll need to configure this plugin the same way. You should be able to use `additionalData` as explained in the README for this plugin: https://github.com/mrmckeb/typescript-plugin-css-modules?tab=readme-ov-file#options

That makes so much sense I'm embarrassed that I even asked. Thanks a lot! 🙏

**Comment by mrmckeb** [comment]
We only added it somewhat recently I think, don't stress!

Most of open source is troubleshooting - you should see the questions I've asked!
