### ISSUE TITLE
Moderate audit issue in dependency

### ISSUE THREAD

**Issue by FBNitro** [mrmckeb/typescript-plugin-css-modules#225]
**Describe the bug**
There is a moderate audit issue on yaml@1.10.2, which postcss-load-config@3 depends on.  postcss-load-config@4 has upgrade to yaml@2.x which has a resolution for the audit issue.

https://github.com/advisories/GHSA-f9xv-q969-pqx4

This project could be updated to postcss-load-config@4 to resolve the issue.

**To Reproduce**
Run `npm install` then `npm audit` on this repository.

**Expected behavior**
No audit issues

**Desktop (please complete the following information):**
- OS: Windows 10

**Additional context**
Here's a dependency tree showing the path:
```
│ └─┬ typescript-plugin-css-modules@5.0.1
│   └─┬ postcss-load-config@3.1.4
│     └── yaml@1.10.2 deduped
```

**Comment by mrmckeb** [comment]
Unfortunately they dropped the sync API in v4.
https://github.com/postcss/postcss-load-config/blob/main/CHANGELOG.md#breaking-changes

At least today, TS plugins can't be async.
https://github.com/microsoft/TypeScript/issues/29361

I'd love help solving this though if you have any ideas/suggestions.

**Comment by FBNitro** [comment]
It appears that the yaml usage in postcss-load-config is limited to just a .parse call, which is unchanged in yaml@^2 and should be completely backwards compatible.  So in theory we could branch it and update it if needed.

But, that said, it appears that the audit issue has been nullified, the affected versions on the issue were changed to >= 2.00, < 2.2.2.

So this is no longer an issue.  Thanks for looking at it quickly though.

**Comment by mrmckeb** [comment]
I'll close this off for now as there's not much else we can do.
