### ISSUE TITLE
Autocomplete not working with global path

### ISSUE THREAD

**Issue by abaksha-sc** [mrmckeb/typescript-plugin-css-modules#227]
**Describe the bug**
Next.js often use global path alias `@` for sources (defines in `tsconfig.json` through `"baseUrl": "."` and `"paths": { "@/*": ["./src/*"] }`).  
And in this case autocomplete for CSS-module doesn't work.

**To Reproduce**

1. Go to [sandbox sources](https://codesandbox.io/p/sandbox/silly-cherry-yn2crj?file=%2Fsrc%2Fpages%2Findex.tsx%3A1%2C30)
2. Make sure first line is defined with absolute path: `import styles from "@/styles/home.module.scss";`
3. Over cursor to variable `styles` on line 8.
4. See the variable definition as 

![image](https://github.com/mrmckeb/typescript-plugin-css-modules/assets/37663273/a0d28315-2f2f-4b1c-b54c-b9bcc2734269)

**Expected behavior**
Please modify sources: 
1. comment first line with absolute path `import styles from "@/styles/home.module.scss";`
2. uncomment second line with relative path `import styles from "../styles/home.module.scss";`
3. Hover variable `styles` on line 8.

In this case you will see the valid definition with CSS-classes as object keys like:

![image](https://github.com/mrmckeb/typescript-plugin-css-modules/assets/37663273/8967c37c-96ad-4eb1-afc5-4ac3cc9b8b3c)

**TypeScript version**: 5.0.4
**Plugin version**: 5.0.1

**Comment by hou5emd** [comment]
@abaksha-sc  check on 4.2.3, because it`s work for me

**Comment by SLTKA** [comment]
I think issue is in this line https://github.com/mrmckeb/typescript-plugin-css-modules/blob/2e502074b9f370dd8d970bc7e6e8a970bf57ba59/src/index.ts#L157 `getResolvedModuleWithFailedLookupLocationsFromCache` is not defined by default in TS, like in my VSCode language server it stays `undefined` for TS 4.9.5 and 5.1.3 (haven't tested others).

Which config can I use to have `getResolvedModuleWithFailedLookupLocationsFromCache` defined?

Another challenge that we can override `isCSS` but not `isRelative`. Maybe having custom resolver override would be the easiest solution if this is possible, or fallback to Node resolution (just thinking at loud, haven't check this ideas)

**Comment by marcoms** [comment]
Also facing this issue so having to just use relative paths which isn't ideal. It would be great to get hints working for absolute paths, especially as the '@/...' style is becoming more common.

**Comment by sshrshnv** [comment]
@mrmckeb when will this fix be published in npm?
