### ISSUE TITLE
The ts type prompt is not updated after modifying the scss file

### ISSUE THREAD

**Issue by vhvy** [mrmckeb/typescript-plugin-css-modules#228]
**Describe the bug**
The index.tsx file introduces index.scss, and index.scss introduces common.scss through @import. After modifying common.scss, the classes type definition in index.tsx is not updated,and the type definition will only be updated after modifying index.scss (such as adding a space and saving it)

**Expected behavior**
After modifying the common.scss file, the classes type in the a.tsx file should be updated

**Screenshots**

![1](https://github.com/mrmckeb/typescript-plugin-css-modules/assets/45645834/3e7b5c7d-a39a-4160-870d-d85c66ace3c6)

![2](https://github.com/mrmckeb/typescript-plugin-css-modules/assets/45645834/2e9fbc20-22b1-4188-be31-f15161a66ac0)

**Comment by mrmckeb** [comment]
Unfortunately I don't think we can change this behaviour. This is a TypeScript plugin and we rely on the files/updates from TypeScript's server.
