### ISSUE TITLE
Allow to create configurable extensions for VSCode based on this plugin

### ISSUE THREAD

**Issue by alexojegu** [mrmckeb/typescript-plugin-css-modules#233]
**Is your feature request related to a problem? Please describe.**
Allow to create configurable extensions for VSCode based on this plugin.

**Describe the solution you'd like**
Implement `onConfigurationChanged` for [plugin configuration](https://code.visualstudio.com/api/references/contribution-points#Plugin-configuration).

**Describe alternatives you've considered**
From what I understand currently it is only possible to create non-configurable extensions for VSCode based on this plugin.

**Comment by mrmckeb** [comment]
Hi there, I'd be very open to this if you'd like to create a PR!

**Comment by ssddi456** [comment]
maybe this pl #149 could help you @alexojegu

**Comment by mrmckeb** [comment]
Closing this off as it's not something I have time for right now. PRs welcome though!
