### ISSUE TITLE
Plugin causes error in VSCode with TypeScript 5.2.2

### ISSUE THREAD

**Issue by alexschrod** [mrmckeb/typescript-plugin-css-modules#236]
This bug was [originally reported to TypeScript itself](https://github.com/microsoft/TypeScript/issues/55673#issuecomment-1717204033), but turns out to be [caused by the `typescript-plugin-css-modules` plugin](https://github.com/microsoft/TypeScript/issues/55673#issuecomment-1722678352).

A fix is suggested by members of the team starting at [this comment](https://github.com/microsoft/TypeScript/issues/55673#issuecomment-1724293216) and down to the end. I'll quote the most pertinent stuff here:

> The plugins shouldnt be using `languageService.getProgram()` instead ~~`project.getProgram()`~~ to ensure there is no issue with synchronization between LS and project. This looks like external issue with the plugin rather than Typescript itself

> Sorry. Got this wrong the first time. its `project.getLanguageService().getProgram()`
> 
> This makes sure that language service gets updated through project and the states are matched.

**Comment by mrmckeb** [comment]
Hi @alexschrod, we don't use that method in this project. We actually had a member of the TS team (@jakebailey) help us refactor/migrate the plugin when TypeScript 5.0 launched too.

**Comment by mrmckeb** [comment]
@alexschrod did you have a way to reproduce this or any debug logs? Otherwise I'll try and reproduce from what I can see in comments.

**Comment by mrmckeb** [comment]
As we've had no other reports in almost a month, and we don't have any reproduction steps or logs, I'll close this off.

Please re-open if this issue reoccurs. We obviously don't want to have people experience strange crashes/issues.
