### ISSUE TITLE
Current customMatcher does not match stylus files

### ISSUE THREAD

**Issue by b13nxx** [mrmckeb/typescript-plugin-css-modules#237]
I couldn't get it to work with the Stylus even though I installed it as documented, even the renderer options for the Stylus are documented. After some time, while going through the issues, I realized that the default value of the _customMatcher_ option (which is `"\\.module\\.(c|le|sa|sc)ss$"`) leaves out the Stylus files 😥

Shouldn't the Stylus files be added by default? Something like this: `"\\.module\\.((c|le|sa|sc)ss|styl)$"`

**Comment by mrmckeb** [comment]
Hi @b13nxx, Stylus support was added a while after others, so I think this just slipped. I'm not opposed to adding that if you want to create a PR?

**Comment by mrmckeb** [comment]
This was my mistake, this was added - but the README was not updated.
