### ISSUE TITLE
Is version 5 backwards compatible with weback and CRA

### ISSUE THREAD

**Issue by kintz09** [mrmckeb/typescript-plugin-css-modules#242]
- Does a compatibility chart of any details like that exist for this plugin?
- Does anyone know if version 5 of the plugin is backwards compatible with create react app (CRA) and webpack?
- Is it safe to upgrade the plugin to version 5 in a CRA4 project using webpack 4?

**Comment by mrmckeb** [comment]
Hi @kintz09, this plugin _shouldn't_ be incompatible with older versions of CRA. As I was a maintainer of CRA, this plugin was originally built for use alongside CRA, but I mainly test alongside Next.js today.

We don't have a compatibility chart as we aim for 100% compatibility with supported CSS syntaxes. Depending you your project set up, you may need to provide some additional configuration to this project though.

Webpack isn't used by the plugin at all. Version 5 of the plugin added support for TypeScript 5 and had some major changes under the hood, but compatibility should have remained the same - we only dropped support for TypeScript 3.x.

If you do encounter any issues, please feel free to open an issue here :)

**Comment by kintz09** [comment]
Thanks @mrmckeb! This is very helpful. I don't think I've run into a problem with this plugin besides with the version of Typescript. I knew there was some typescript compatibility to be aware of but couldn't remember if that was just typescript or other CRA dependencies as well.

Its great to hear webpack is not a variable in this at all. :)

In the future it would be helpful if there was a place to reference which versions of typescript are compatible with which version of this plugin.

Thank you so much for your quick response!
