### ISSUE TITLE
Including this plugin in WebStorm projects breaks TS type checking

### ISSUE THREAD

**Issue by ekilah** [mrmckeb/typescript-plugin-css-modules#243]
**Describe the bug**
I recently updated to `5.0.1` of this plugin and regular TS type checking in JetBrains WebStorm doesn't work unless I comment out the `plugin` definition in my `tsconfig`.

**To Reproduce**
Making a type error (typo on a variable name, etc) in my React TypeScript project doesn't produce any errors in Webstorm if I include this plugin in `tsconfig`. (Note: CSS module stuff, like hovering over an import to see its type or errors about classnames not existing) doesn't work either way, either, which is obviously related)

**Expected behavior**
Both regular type checking and the extra stuff this plugin should be adding work in WebStorm when this plugin is enabled.

**Screenshots**
With the plugin disabled, by commenting it out in my `tsconfig`

![image](https://github.com/mrmckeb/typescript-plugin-css-modules/assets/3213339/c9a1e64c-9ece-4a3d-8409-32eefdd73a3e)
<img width="658" alt="image" src="https://github.com/mrmckeb/typescript-plugin-css-modules/assets/3213339/65ef80b9-7233-4ec6-b97e-7429bded1a32">

With it enabled:

![image](https://github.com/mrmckeb/typescript-plugin-css-modules/assets/3213339/bc0c411b-50f6-4243-a79b-2e6cace654d5)
![image](https://github.com/mrmckeb/typescript-plugin-css-modules/assets/3213339/f2f345dd-ef75-49b4-ad79-4166a87c6fd6)

- OS: MacOS Monterey 12.7
- plugin version 5.0.1
- TS version 5.1.6

I'm more than happy to help debug this, since you may not have WebStorm access, though there is a free trial period. I just don't know what I might be looking for.

**Comment by ekilah** [comment]
the same problem appears to happen on this plugin's relatively newly released `5.0.2`, no change.

**Comment by mrmckeb** [comment]
Hi @ekilah! Sorry you've hit this.

To clarify, are you saying this was fine with version 4.x for you? Have you also updated to TypeScript 5.x?

The plugin should fail and just return an empty object `{}` if something is wrong, but it's possible that something else is happening here. Are you able to share the TypeScript server logs?
https://stackoverflow.com/questions/70487104/webstorm-see-typescript-server-logs

**Comment by ekilah** [comment]
I actually updated from this plugin's `3.4.0` -> `5.0.1`, I'd have to test 4.x separately. I only really updated it to get the fixes from 

- https://github.com/mrmckeb/typescript-plugin-css-modules/pull/201

because I was cleaning up some old dependencies in my project. And it looks like this plugin's `4.2.0` would provide that update. However, yes, the project is using TS 5.1.6 (and my editor is using the same version as the project), and I don't know if `4.2.0` will work with TS 5?

**Comment by ekilah** [comment]
I happened to stumble on https://github.com/microsoft/TypeScript/issues/55673 while debugging more. I left a detailed comment there with some logs attached: https://github.com/microsoft/TypeScript/issues/55673#issuecomment-1776235644

**Comment by mrmckeb** [comment]
You need to use 5.x of this plugin for TypeScript 5.x support. Not intentionally aligned in versions, but there were some breaking changes shipped with that release. Have you tried downgrading to the previous TS release to see if you still encounter that issue?

Thanks for also posting on the TS thread. Perhaps they can provide some more insight. There's obviously something going on, but I'm not sure what and it's seemingly very rare that people hit it - as this extension gets 275k weekly downloads, and I know many of those use the latest TS version.

**Comment by ekilah** [comment]
I switched over to a smaller side project that was easier to test things on (and to produce those logs I posted), where it is also easy to switch between TS 4 and TS 5.

There, I can't reproduce the issue on TS 4 and plugin 4.2.3 - a whitespace change to my `tsconfig` file there does reload the TS server (I see the errors in a TS file I've produced to test flash for a second) but it comes back immediately.

Unfortunately, in the main project i was posting about originally, downgrading to TS 4 isn't a realistic option...

**Comment by mrmckeb** [comment]
Thanks for trying to create a reproduction, I appreciate the effort. As you can imagine, it makes debugging significantly (even infinitely) easier.

Could you try a release like these?
- https://www.npmjs.com/package/typescript/v/5.0.4
- https://www.npmjs.com/package/typescript/v/5.1.3

**Comment by ekilah** [comment]
5.1.3 seems to work: https://github.com/microsoft/TypeScript/issues/55673#issuecomment-1776281177

I didn't bother trying `5.0.4` since `5.1.3` worked, but lmk if you want me to. (I've spent most of my work day on debugging this slowly but I could try tomorrow if so 😛)

**Comment by mrmckeb** [comment]
No, that's plenty - thanks! Let's see if the TS team has any thoughts.

**Comment by mrmckeb** [comment]
Closed by #244 for now. We'll reopen if the TS team think there are changes we can make in future. Thanks again!
