### ISSUE TITLE
refactoring support in vscode

### ISSUE THREAD

**Issue by nitzcard** [mrmckeb/typescript-plugin-css-modules#245]
in vscode when refactoring css class it doesn't work.

**Comment by mrmckeb** [comment]
Hi @nitzcard, this is a limitation of this plugin, as it's actually parsing TypeScript a generated list of type definitions - TypeScript doesn't support CSS, and as far as I know there isn't any way to make this work.

I am trying though, and when I can, I try to find creative ways to enable features. For example, `goToDefinition` mostly works now, but still needs improvement.
