### ISSUE TITLE
Relative paths using typescript paths options not being resolved

### ISSUE THREAD

**Issue by bsunderhus** [mrmckeb/typescript-plugin-css-modules#25]
Apparently, the plugin is not able to resolve the types for files that are relative to some path declaration on the typescript configuration.

My `tsconfig.json`: 

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "~": ["./src/index.tsx"],
      "~/*": ["./src/*"]
    },
    "sourceMap": true,
    "target": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "strict": true,
    "isolatedModules": false,
    "esModuleInterop": true,
    "declaration": false,
    "resolveJsonModule": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "esnext"
    ],
    "plugins": [
      {
        "name": "typescript-styled-plugin",
        "tags": [
          "css"
        ]
      },
      {
        "name": "typescript-plugin-css-modules",
        "options": {
          "customMatcher": "\\.(sc|c)ss$",
          "camelCase": "only"
        }
      }
    ],
    "typeRoots": [
      "./node_modules/@types",
      "./@types"
    ]
  },
  "include": [
    "src",
    "webpack"
  ]
}
```

In my *TS* file if I import a style by an absolute path, everything works fine, but if the file path is relative to the `~` it simply doesn't work

```ts
import globalStyle from '~/styles/style.scss' // Doesn't work at all
import globalStyle2 from '../../styles/style.scss' // Works just fine
```

- OS: OSX 10.14.5
- Browser: Chrome
- Version: 75

**Comment by mrmckeb** [comment]
Thanks for raising this, and for the detailed reproduction instructions.

This is related to #24, and I'm working on it right now. Hopefully I'll release a fix today.

**Comment by nyngwang** [comment]
@mrmckeb Sorry for tagging you directly. But I need your help in that: is it correct to say that by only setting `compilerOptions.paths` in tsconfig.json, no intellisense for importing CSS files with alias paths? If so, the current way to achieve this is by a plugin, for example, this one you made. Correct?
