### ISSUE TITLE
Question: Is it only for IDE completion or build time checking

### ISSUE THREAD

**Issue by testarossaaaaa** [mrmckeb/typescript-plugin-css-modules#27]
So if I make a mistake and run the tsc directly from a console will I get an error?

**Comment by mrmckeb** [comment]
Hello @testarossaaaaa, good question.

Right now, the TypeScript team don't support plugins during build-time, only development, but this is something many members of the community want to see changed.

If you really need this, you can consider using [`ttypescript`](https://github.com/cevek/ttypescript) with a transform, or using a tool that writes `.d.ts` files to disk. Neither solution are ideal...

**Comment by memark** [comment]
@mrmckeb This is of course unfortunate (and not your fault). I think it would be very helpful to document this limitation in the README. I just spent a lot of time trying to get this plugin working at build time. :/

**Comment by mrmckeb** [comment]
Thanks for the feedback @memark, I recently added this to the README:
https://github.com/mrmckeb/typescript-plugin-css-modules#about-this-plugin

Does that cover it?

**Comment by memark** [comment]
That looks great, thanks! @mrmckeb
