### ISSUE TITLE
include mixins in scss cause whole file not working

### ISSUE THREAD

**Issue by zaaack** [mrmckeb/typescript-plugin-css-modules#29]
**Describe the bug**
```scss 
// index.module.scss
.cls { 
  @include line-clamp(3);
}

```
This will cause types missing.

![image](https://user-images.githubusercontent.com/5233940/61117644-8e0b5580-a4c9-11e9-9fb6-3444434206dc.png)

**To Reproduce**

1. create index.module.scss with mixins `.cls { @include line-clamp(3); }`
2. open ts file in vscode

**Expected behavior**
index.module.scss should be working

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS
- Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mrmckeb** [comment]
Thanks for raising this @zaaack. I'll take a look at it today and try to get a fix out in the next 24 hours.

**Comment by mrmckeb** [comment]
This is now released. Thanks again!

https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v1.2.1
