### ISSUE TITLE
How can I help this lovely project get merged upstream into CRA?

### ISSUE THREAD

**Issue by onpaws** [mrmckeb/typescript-plugin-css-modules#32]
Thanks for making this project, it's cool and thanks to your efforts I was able to write my React components using TypeScript and include CSS Modules. Nice to have both!

Regarding this [comment](https://github.com/facebook/create-react-app/pull/5877#issuecomment-474950423)
"Closing this off until plugins work at build-time."

It sounds like I should direct my attention to Microsoft's TS team so they support plugins at build time. I'm not a super expert in what it takes to deliver this but if I understand right, this would be what it takes for the CRA project to ship official support for this feature, right?

**Comment by mrmckeb** [comment]
I'm glad it helped you! Thanks for the feedback.

Yes, so the big blocker here is that the TypeScript team have yet to provide a way for this to work at build-time... which is not ideal. It was obviously me that made the call to close the issue off at that time, and I do wish we could support it now.

We could consider moving CRA to https://github.com/cevek/ttypescript, but I feel that's imperfect too. For now - and I haven't tested this - you may be able to use it with that library to get what you need. I'll also investigate documenting that in this repo.

The related issues at TypeScript are:
- https://github.com/microsoft/TypeScript/issues/14419
- https://github.com/microsoft/TypeScript/issues/16607

Thanks again for your feedback.

I'll close off the issue, but feel free to keep the conversation going here if you have any ideas :)
