### ISSUE TITLE
tsserver logging

### ISSUE THREAD

**Issue by dagda1** [mrmckeb/typescript-plugin-css-modules#36]
**Is your feature request related to a problem? Please describe.**
There is no logging throughout the plugin and errors are just getting swallowed, for example in [cssSnapshots](https://github.com/mrmckeb/typescript-plugin-css-modules/blob/develop/src/helpers/cssSnapshots.ts#L63), the catch block returns `{}`. 

```
    return extractICSS(processedCss.root).icssExports;
  } catch (e) {
    return {};
  }
```

It took a lot of painstaking logging to find out that an exception was being swallowed.

**Describe the solution you'd like**

There is a logger that gets passed into the `create` function as part of the `info` object, e.g.

```javascript
  function create(info) {
      var logger = info.project.projectService.logger;
```

There is a `TSS_LOG` environment variable that when set allows you to log to the console or a file, e.g.

```bash
export TSS_LOG="-level verbose -file /Users/me/.tslog"
```

You can then see the log messages, it took me a long time to find the actual error.

This is not a criticism, thank you for writing this library, I think it most needed.

**Comment by mrmckeb** [comment]
Hi @dagda1, I have also faced this issue and it needs to be addressed. Would you like to raise a PR? If not, I could probably look at it this weekend.

**Comment by dagda1** [comment]
@mrmckeb very happy to raise a PR.  Very happy to help, I've been looking for ts css module support for a long time.
