### ISSUE TITLE
tilde sass import from node_modules library

### ISSUE THREAD

**Issue by dagda1** [mrmckeb/typescript-plugin-css-modules#37]
**Describe the bug**

I have a sass file that includes an `@import` to a file in a package in `node_modules`

`@import '~@cutting/component-library/src/styles/_index.scss';`

I get this error:

```
Can't find stylesheet to import.

@import '~@cutting/component-library/src/styles/_index.scss';
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This is getting raised from this line in `cssSnapshots.js`

```javascript
            transformedCss_1 = sass
                .renderSync({
                data: css,
                includePaths: [filePath],
            })
                .css.toString();
```

**To Reproduce**

1. add an import to a package in node_modules

**Expected behavior**
The sass file should be properly parsed and the declarations created

**Desktop (please complete the following information):**

- OS: OSX

Perhaps the `node_modules` folder should be added to `includePaths` in the call to `sass.renderSync`

**Comment by mrmckeb** [comment]
Hi @dagda1, you might be right on the suggested solution, this is definitely something we can add in.

Unfortunately these things are hard, as we can't know a user's configuration for Sass/Wepback/etc, so everything we're doing here is best effort.

If you want to take a swing at this, let me know - if not, that's fine. I'm on a business trip in London and time is short for the next 2-3 weeks... but I can find time this weekend for sure.

**Comment by dagda1** [comment]
@mrmckeb This might be trickier than I first thought.  The tilde thing is what sass-loader uses, so I'm exploring how they handle it. 

already looking into it :), do you have any other tips for debugging apart from lots of `logger.info` statements?

**Comment by dagda1** [comment]
@mrmckeb I've been doing some detective work and the `~` was actually a workaround in the sass-loader that was fixed in [this PR](https://github.com/webpack-contrib/sass-loader/pull/447/files).

If I remove this tilde from my import and include `node_modules` in the `includePaths` in renderSync then all is good.

```javascript
      transformedCss = sass
        .renderSync({
          data: css,
          includePaths: [
            filePath,
            'node_modules'
          ],
        })
        .css.toString();
```

The above will fix my problem if I remove the tilde and add `node_modules` to `includedPaths`.

Is this a wise first step fix to just add `node_modules` as a string literal to the `includePaths`?

1.  In the crazy world of the monorepo, `node_modules` might not be in the same path as the `process.cwd()`.
2.  Should we give the user the ability to add their own paths to the `includePaths` in the options, for weird situations like the monorepo?.
3.  I'll need to think how best to tests this, I think I can just create a `node_modules` directory in the `__tests__` directory.

**Comment by mrmckeb** [comment]
Again, sorry for the slow reply... I'm in London working still, I'll not be back home for two more weeks, but I'm trying to find time where possible.

I agree with you, I think adding an option for this makes sense. We could just call it `paths` as in `tsconfig.json`.

I'm on the Create React App team, we've moved to using TypeScript's settings (from `tsconfig.json` or `jsconfig.json`) where possible, but again I think your suggestion is a good fix for now.

I can add this in before release of 1.3.0, as it'll be a quick one.

**Comment by amelekhin** [comment]
> But allowing the user to supply includedPaths might get around a lot of problems in the same way as webpack allows you to supply modules

This should work fine for imports that are located in `node_modules` or linked through `resolve.modules`, but I doubt it would work for `resolve.alias` as well. It feels like `includedPaths` should utilize the `compilerOptions.paths` option's format.  I wonder, is there a way to make use of `compilerOptions.paths` values directly in the plugin?

**Comment by mrmckeb** [comment]
Yes, that's a good idea @amelekhin - and sorry for the delay, I've been away for two weeks.

Would you like to take a look at that?

**Comment by mrmckeb** [comment]
Hi, I've just released v2.0.0 which should solve this issue by allowing users to pass through options to Less and Sass.

Release notes and migration steps can be found here: https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v2.0.0

Please let me know if you have any feedback!

**Comment by dagda1** [comment]
@memckeb i’m sorry but which of the new options solves this problem?

**Comment by mrmckeb** [comment]
Sorry I wasn't clear @dagda1. You can now pass in (via options) paths to the Sass/Less renderers, which will allow you to add to or override default settings. 

https://github.com/mrmckeb/typescript-plugin-css-modules#rendererOptions

We could also add 'node_modules' the paths directly if you think that would help, I have no concern with that and could get that change out today/tomorrow.
