### ISSUE TITLE
Monorepo usage

### ISSUE THREAD

**Issue by xiaoxiangmoe** [mrmckeb/typescript-plugin-css-modules#4]
It won't work in monorepo mode(yarn workspace) if I run my workspace version of TypeScript.

Reproduce demo: https://github.com/xiaoxiangmoe/monorepo-error-typescript-plugin-css-modules

**Comment by mrmckeb** [comment]
Thanks for reporting this @xiaoxiangmoe, and for the reproducible demo - that'll be very helpful.

I'll take a look tonight and try to resolve this.
