### ISSUE TITLE
The directory hierarchy is very deep and leads to Problem

### ISSUE THREAD

**Issue by vvni** [mrmckeb/typescript-plugin-css-modules#44]
**Describe the bug**
The directory hierarchy is very deep and leads to Problem
**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by mrmckeb** [comment]
Hi @vvni, can you please provide more information on this ticket? I don't quite understand the issue as you're reported it.

**Comment by vvni** [comment]
Ok, sorry. I was busy working before, and I didn't describe it clearly. I will add later

**Comment by vvni** [comment]
@mrmckeb, After updating the latest version, I found that my problem was solved.
