### ISSUE TITLE
Does not generate definitions for imported stylesheets

### ISSUE THREAD

**Issue by k-g-a** [mrmckeb/typescript-plugin-css-modules#48]
**Describe the bug**

Even if we could use `@import` statements without throwing an error about plugin's async mode (i.e. via `postcss-import-sync2` plugin) - we still don't get proper typings for such files.

**To Reproduce**

Assuming we have:
1) `./foo/index.css` with some relative imports:
```
@import './A.css'
@import 'B.css'
```
2) corresponding files  `./foo/A.css` & ``./foo/B.css``
3) the following `postcss.config.js`:
```
module.exports = { plugins: [require('postcss-import-sync2')()] };
```
4) and `./some.js` file importing styles:
```
import styles from './foo/index.css'
```

We won't get typings for `styles` other than `{}`, because of the resolution error (from TSS_LOG):
```
Info NNN  [typescript-plugin-css-modules] Failed Error: Failed to find 'A.css'
in [
  C:\Git\some-project-root
]
```

**Expected behavior**

Get proper typings.

**Additional context**

This bug occurs because of the following reasons:

1) `postcss-import-sync2` plugin looks for sourceFile in AST statement: `atRule.source.input.file` ([here](https://github.com/longlho/postcss-import-sync2/blob/master/lib/index.js#L170))
2) it's missing so the plugin falls back to `options.root`, which is `process.cwd()` (or passed option). at this point we could fix the problem by manually specifying `path: []` option for `postcss-import-sync2` plugin, but thats not future-proof solution involving some magical knowledge to be shared almong developers.
3) going one step further, the `atRule.source.input.file` field is missing because `DtsSnapshotCreator` does not provide the `from` option to `postcss.process` [here](https://github.com/mrmckeb/typescript-plugin-css-modules/blob/develop/src/helpers/DtsSnapshotCreator.ts#L61).

A simple one-line change (adding `{from: fileName}` as a second argument) fixes the problem for us, but i'm not sure if this could break some common setups.

By the way, passing the same `fileName` as `filename` option to `less.render` alongside with setting `syncImport: true` should fix #47.

I can make a PR if it's proven to be the proper fix.

**Comment by mrmckeb** [comment]
Hi @k-g-a, that sounds good to me - thanks!

I don't think it would break setups, but we could certainly test it. If you can make the PR with or without tests, that would be great - I can always add tests before getting the next release out this weekend.

**Comment by k-g-a** [comment]
Great news, will make 2 PR (for this and for less) tomorrow

**Comment by mrmckeb** [comment]
Thank you!

**Comment by k-g-a** [comment]
No problem. Those changes are quite small and are closely related, so I decided to make them via single PR :)
