### ISSUE TITLE
Does not use SASS_PATH environment variable when resolving imports

### ISSUE THREAD

**Issue by PsiRadish** [mrmckeb/typescript-plugin-css-modules#49]
**Describe the bug**
I have a sass file containing variable/function/mixin stuff located at `/src/theme/_module-basics.scss`.
In my *.env* file I have
```
SASS_PATH=./src/theme
```
which allows me to import *_module-basics.scss* into any CSS module regardless of its location with just
```scss
@import "module-basics";
```  
  
However, after importing such a CSS module into a tsx file, it is typed only as `{}` in VS Code, and I see this in the TS Server log:
```
Info 56   [10:6:34.575] [typescript-plugin-css-modules] Failed Error: Can't find stylesheet to import.
  ╷
1 │ @import "module-basics";
```
Only if I change the `@import` to use a path relative to the module file, like say...
```scss
@import '../theme/module-basics';
```
...do I get a proper type definition for the CSS module.

**To Reproduce**
1. Add the following file/folder structure to a CRA project configured to use `typescript-plugin-css-modules`:
   ```
   (root)
   ├ .env
   └ /src
     ├ App.tsx
     ├ App.modules.scss
     └ /theme
       └ _module-basics.scss
   ```
1. File contents:
   - *.env*
     ```
     SASS_PATH=./src/theme
     ```
   - *_module-basics.scss*
     ```scss
     $nice-color: #FF0080;
     ```
   - *App.modules.scss*
     ```scss
     @import "module-basics";     
     .nicely-colored {
         color: $nice-color;
     }
     ```
   - *App.tsx*
     ```tsx
     /* React, etc. imports */
     
     import styles from './App.module.scss'; // styles assigned Type of {}
     
     function App(props: {}) {
         return (
             <span className={styles["nicely-colored"]}>This is nice.</span> // angry zigzag under styles["nicely-colored"]
         )
     }
     ```
1. Observe `styles` in *App.tsx* is typed as `{}`, causing an angry zigzag in VS Code under `styles["nicely-colored"]`

**Expected behavior**
This plugin and/or its dependencies are able to use the contents of SASS_PATH to resolve `@import "module-basics"` in *App.module.scss*.
Following which, `styles` in *App.tsx* is provided a Type based on the classes/ids in *App.module.scss*, so there is no angry under `styles["nicely-colored"]`.

**Desktop**
- OS: Windows 10

**Comment by mrmckeb** [comment]
Thanks for this. I can take a look at it over the weekend.

I found documentation on this and will look at this over the weekend - unless you'd like to raise a PR @PsiRadish?

**Comment by PsiRadish** [comment]
Sure.

**Comment by mrmckeb** [comment]
Hi @PsiRadish, we've just released v2.0.0 which includes this PR and other changes.

Release notes and migration steps can be found here: https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v2.0.0

Please let me know if you have any other issues or feedback! And thanks for your patience.

**Comment by PsiRadish** [comment]
This doesn't work with relative paths in `SASS_PATH`.  I mean, it technically doesn't work at all most of the time because of #56, _but_ even if that were fixed, relative paths in `SASS_PATH` would be resolved relative to `process.cwd()` which is VS Code's installation directory.

I fixed this in #51 by replacing relative paths in `SASS_PATH` with resolved absolute versions, but [it was removed](https://github.com/mrmckeb/typescript-plugin-css-modules/commit/3ce541987ab4ee093d48b77451cab00091fda647#diff-f41e9d04a45c83f3b6f6e630f10117feL202-L213) before the release, probably because it's in the middle of my logic that manually parses the `.env` file so you thought you didn't need it.  There is [an earlier version of my code](https://github.com/mrmckeb/typescript-plugin-css-modules/pull/51/commits/24c91c576470acef3aaa015e0de2e724cd5ee4e7#diff-f41e9d04a45c83f3b6f6e630f10117feR192-R206) that works with `dotenv`, though; shall I make another pull request?

**Comment by mrmckeb** [comment]
@PsiRadish, thanks for that investigation.

That code removal was my mistake, I refactored that area and removed that code without realising that I'd also removed the normalisation.

I'd rather not have _too_ much logic to cover different cases - but I understand that sometimes that isn't enough.

So yes, I think it's fine to add this back in. I can do it along with #56, or you can create a PR - let me know!

**Comment by PsiRadish** [comment]
Probably quicker to let you do it with #56.
