### ISSUE TITLE
Imported less files not found when using `tsc`

### ISSUE THREAD

**Issue by krawaller** [mrmckeb/typescript-plugin-css-modules#57]
Just to join the choir - thank you for an amazing tool! 

It works flawlessly in the editor, but I'm having trouble getting `tsc` to work. I set up a minimal repo reproducing the issue here: https://github.com/krawaller/ts-less-demo

It includes very minimal `foo.less` file:

```less
.less {
  color: green;
  &IsMore {
    background-color: brown;
  }
}
```

...and an equally minimal `foo.ts` that consumes it:

```typescript
import { lessIsMore } from "./foo.less";

export const favouriteStyle = lessIsMore;
```

The `tsconfig.json` includes the `src` folder containing both the above files, and includes the plugin:

```json
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "typescript-plugin-css-modules",
        "options": {
          "customMatcher": "\\.(c|le|sa|sc)ss$"
        }
      }
    ]
  },
  "include": ["src"]
}
```

Running the classic "type health check" `tsc --noEmit` fails, complaining that the `.less` file isn't found:

![image](https://user-images.githubusercontent.com/249764/67263476-8ab03e80-f4a8-11e9-923c-a1456f6aed38.png)

When checking the "compiled" config by doing `tsc --showConfig`, I can see that it adds a `files` prop containing all the `.ts` files inside the included folder (in my case just `foo.ts`):

```json
{
    "compilerOptions": {
        ...
    },
    "files": [
        "./src/foo.ts"
    ],
    "include": [
        "src"
    ]
}
```

If I try to cheekily add `src/foo.less` to `files` myself, the compiler will complain about unsupported file types:

![image](https://user-images.githubusercontent.com/249764/67263719-2f328080-f4a9-11e9-8302-f19ded8fe5b5.png)

I feel like I'm missing something blatantly obvious, and humble apologies if that is the case, but I can't for the life of me find anything related in the docs or other issues. How do you all make the ts compiler and the plugin play nice together?

**Comment by mrmckeb** [comment]
HI @krawaller, I think you missed the step here: https://github.com/mrmckeb/typescript-plugin-css-modules#custom-definitions

`tsc` won't run this plugin during build (the TypeScript team are looking into this), so you need to tell it what this file is :)

**Comment by krawaller** [comment]
Argh, I fooled myself, apologies @mrmckeb! I did indeed forget it at first, then added it, but it still wasn't working. However, I failed to notice that the error message turned from the above into this:

![image](https://user-images.githubusercontent.com/249764/67265755-d1a13280-f4ae-11e9-912f-eb9b3aad2d1b.png)

But if I refactor `foo.ts` to not use the named exports directly...

```typescript
import styles from "./foo.less";

export const favouriteStyle = styles.lessIsMore;
```

...then it works!

So, I guess the takeaway is that the named exports won't work with `tsc`?

**Comment by krawaller** [comment]
Also, for anyone else stumbling across this issue´ having been as silly as me: My original mistake was to put the `.d.ts` file with the custom definitions outside of the folder targeted by the `includes` in `tsconfig.json`. TS newbie mistake.

**Comment by mrmckeb** [comment]
> So, I guess the takeaway is that the named exports won't work with tsc?

Yes, this is an issue... and it's been a long long conversation with the TypeScript team...

This is one of the threads: https://github.com/microsoft/TypeScript/issues/14419

Sorry I can't help further, and thanks for the feedback!
