### ISSUE TITLE
Unsure how to configure autocomplete in VSCode

### ISSUE THREAD

**Issue by thekevinbrown** [mrmckeb/typescript-plugin-css-modules#61]
**Describe the bug**
These docs seem to be outdated:
https://github.com/mrmckeb/typescript-plugin-css-modules#visual-studio-code

There's no heading anymore for using the workspace version of Typescript, and in my project it's just using the types I set up:

```typescript
declare module '*.module.css' {
	const classes: { [key: string]: string };
	export default classes;
}
```

So autocomplete doesn't do anything other than enforce an object with string keys and string values.

Searching in VSCode itself for a setting called `typescript.tsserver.pluginPaths` doesn't yield anything useful, and I don't know of a way to directly edit the json files anymore.

How do I get this plugin to run in VSCode?

**To Reproduce**

1. Go here: https://github.com/mrmckeb/typescript-plugin-css-modules#visual-studio-code
2. Click on the "Using the workspace version of TypeScript" link
3. No instructions to configure, and searching that page for workspace doesn't yield anything useful.

**Expected behavior**

Expected autocomplete to work in VSCode after setup steps, but as I can't figure out how to fully configure the environment I'm expecting that that's the issue.

**Comment by thekevinbrown** [comment]
Looks like that link moved to here? https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-the-workspace-version-of-typescript

**Comment by thekevinbrown** [comment]
Yup, that fixed it. Steps:

`.vscode/settings.json`:
```
{
  "typescript.tsdk": "./node_modules/typescript/lib"
}
```

Command Pallette -> TypeScript: Select TypeScript Version -> Workspace

So the task is really just to update the docs to point to the new link.

**Comment by mrmckeb** [comment]
I'll try to update the docs this weekend ;) Thanks!

**Comment by mrmckeb** [comment]
Updated in https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v2.1.0.

Thanks again!
