### ISSUE TITLE
Only support relative path import style files？

### ISSUE THREAD

**Issue by vvni** [mrmckeb/typescript-plugin-css-modules#65]
**Describe the bug**
Only support relative path import style files？
Introducing a style file using the webpack path, the style file type definition is not
**To Reproduce**
@import "~styles/var" // error
@import "../styles/var" // bingo

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vvni** [comment]
Sorry, my English is very poor.

**Comment by mrmckeb** [comment]
Hi @vvni, sorry for the very slow reply.

Can you provide a test environment for this? Also, is this for Sass?

I know other users are using this plugin successfully with imports from `node_modules`, so we just need to understand how this case is different :)

**Comment by vvni** [comment]
OK, give an example later

Brody McKee <notifications@github.com>于2019年12月1日 周日20:41写道：

**Comment by vvni** [comment]
@mrmckeb [test example](https://github.com/vvni/yunmeng-mall-webapp).This problem can occur with the Tabbar component in the components folder. I used style-resources-loader. I think this is the same problem. You can test my current problem. I don't quite understand what caused it. Thank you very much!

**Comment by mrmckeb** [comment]
Hi @vvni,

Sorry for the slow reply. You can solve this by following the instructions here:
https://create-react-app.dev/docs/adding-a-sass-stylesheet

In your `.env` file, you should have:
```
SASS_PATH=node_modules:src
```

Then Create React App will allow you to import like this, without any modification in `style-resources-loader` :)
```
@import "styles/var";
```

I tried that in your project, and it works :)

**Comment by vvni** [comment]
@mrmckeb Thank you very much! Let me try。

**Comment by vvni** [comment]
@mrmckeb  😊Thank you. This approach did solve my problem. If I use a style-resources-loader to import a style file, can I generate the type definition of the style correctly?

**Comment by mrmckeb** [comment]
Not at the moment sorry @vvni, this plugin requires that you import files in if you want to use mixins, vars, etc.

I had a look, and I can't see an easy way to do it with the Sass renderer - https://sass-lang.com/documentation/js-api#options. However, I'm always open to a PR if you or someone else would like to submit one!

Let me know if you have any more questions or problems :)
