### ISSUE TITLE
Importing sass file from "node_modules" doesn't work.

### ISSUE THREAD

**Issue by muj-beg** [mrmckeb/typescript-plugin-css-modules#66]
**Describe the bug**
If the CSS module I'm importing in turn imports another SASS file using the "~" prefix, the plugin can't resolve the imported file.

**To Reproduce**
**File: styles.module.scss**:
``` 
  @import "~@blueprintjs/core/lib/scss/variables";
    ... other local style declarations
```

**Expected behavior**
Importing SASS files from the `node_modules` folder using the `~` syntax should work.

**Actual Behavior**
The following error shows up in TS server log:
``` ╷
1 │ @import "~@blueprintjs/core/lib/scss/variables";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  stdin 1:9  root stylesheet
Info 526  [11:17:32.779] [typescript-plugin-css-modules] Stack trace: Error: Can't find stylesheet to import.
  ╷
1 │ @import "~@blueprintjs/core/lib/scss/variables";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  stdin 1:9  root stylesheet
    at Object._newRenderError (\forms\node_modules\sass\sass.dart.js:10819:19)
    at Object._wrapException (\forms\node_modules\sass\sass.dart.js:10669:16)
    at StaticClosure._renderSync (\forms\node_modules\sass\sass.dart.js:10644:18)
    at Object.Primitives_applyFunction (\forms\node_modules\sass\sass.dart.js:1060:30)
    at Object.Function_apply (\forms\node_modules\sass\sass.dart.js:4885:16)
    at _callDartFunctionFast (\forms\node_modules\sass\sass.dart.js:6565:16)
    at Object.renderSync (\forms\node_modules\sass\sass.dart.js:6543:18)
    at Object.exports.getClasses (\forms\node_modules\typescript-plugin-css-modules\lib\helpers\getClasses.js:68:18)```

**Comment by mrmckeb** [comment]
Hi @muj-beg, I'm sorry you're having trouble with this.

Are you able to provide a demo?

Also, do you have `SASS_PATH` set?

**Comment by muj-beg** [comment]
Here's a reproduction of the issue: https://github.com/muj-beg/typescript-plugin-css-modules-issues-66 .
This is a standard CRA project.  There's a style import in `App.tsx` that doesn't resolve:
![image](https://user-images.githubusercontent.com/19629343/70541650-69c5aa80-1b35-11ea-81c4-de2c9c65bfba.png)

Thanks!

**Comment by mrmckeb** [comment]
Hi @muj-beg, I've found the issue and will push a fix shortly. Thanks for your patience!

**Comment by mrmckeb** [comment]
Hi @muj-beg, please try v2.1.2.
https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v2.1.2

If this still fails, please let me know and reopen this issue. I've tested locally with your test project and it seems to be fine now :)

**Comment by muj-beg** [comment]
Just tried v2.1.2 on two project -- and it worked great!

Thanks so much for your quick resolution of this issue, and of course many thanks for the awesome extension in the first place :)

**Comment by mrmckeb** [comment]
No problem, and thanks for the feedback!

**Comment by nokternol** [comment]
I have installed 2.1.2 but am experiencing the same error with importing blueprint 
The error is identical until it reaches your code where it has moved by 2 lines due to added comments.
`(c:\Users\19004432\source\repos\phoenix4.0\FrontEnd\node_modules\typescript-plugin-css-modules\lib\helpers\getClasses.js:70:18)`

I can see the code changes and unit tests and respect this SHOULD be working but cannot figure out from the code what I could change in my config to make this work as it did for @muj-beg 

The test and the reproducible example both used bootstrap. Is it possible that the issue is also with the @ in the package name for blueprint?
This is the only difference I can see...
