### ISSUE TITLE
Autocompletion doesn't work with indented sass

### ISSUE THREAD

**Issue by judehunter** [mrmckeb/typescript-plugin-css-modules#67]
**Describe the bug**
The repo kind-of mentions the support for Sass, though from the looks of it I don't believe it does.
What it appears to support is scss-style syntax, and not sass indent / offside-rule syntax.

**To Reproduce**

1. Add to `tsconfig.json`:
```
"plugins": [
  {
    "name": "typescript-plugin-css-modules",
    "options": {
      "classnameTransform": "camelCase"
    }
  }
]
```
2. Create `example.module.sass`:
```sass
.test
  color: red
```
3. Create `example.tsx`:
```tsx
import React, {FunctionComponent} from 'react';
import style from '../styles/example.module.sass';

export const ExampleComponent: FunctionComponent = ({children}) => (
  <h1>
    {children}
  </h1>
);

```
4. See that autocompletion doesn't work (it does with css and scss though):

![image](https://user-images.githubusercontent.com/32528507/70814180-46b42880-1dcb-11ea-9ee8-111b9e2a019d.png)

**Expected behavior**
Autocompletion should work correctly and intellisense should show the `test` class.
Should work like with css and scss:

![image](https://user-images.githubusercontent.com/32528507/70814280-72cfa980-1dcb-11ea-821e-70d5297a1603.png)

**Workspace:**

- OS: W10
- Package version: 2.1.1
- TS version: 3.7.3

Am I missing something here? Seems like indented sass is a pretty popular choice, I don't know why it shouldn't be supported.

**Comment by mrmckeb** [comment]
Resolved by v2.1.2.
