### ISSUE TITLE
`customMatcher` support

### ISSUE THREAD

**Issue by fmal** [mrmckeb/typescript-plugin-css-modules#7]
**Describe the bug**
I can't get the plugin to work when i specify `customMatcher` such as:
```json
{
  "name": "typescript-plugin-css-modules",
  "customMatcher": "\\.css$"
}
```

When i leave it off then everything works fine.

**To Reproduce**
Add `"customMatcher": "\\.css$"` and use a filename without the `.module` part (`justAFile.css`)

**Additional context**
I quickly browsed the source and noticed that `isRelativeCSS` helper actually uses the default `isCSS` predicate: https://github.com/mrmckeb/typescript-plugin-css-modules/blob/develop/src/helpers/cssExtensions.ts#L6. I guess passing overwritten `isCSS` to `isRelativeCSS` would solve this issue.

Will look into that later in the evening and submit PR if that is the case 😃 

BTW. nice plugin!

**Comment by mrmckeb** [comment]
Thanks again @fmal. This is now released.

On your other issue, I think we can discuss here: #10 ;)
