### ISSUE TITLE
Cannot find module './Component.module.css'

### ISSUE THREAD

**Issue by Nhukangasniemi** [mrmckeb/typescript-plugin-css-modules#74]
**Cannot find module './BuildControle.module.css**

Link for source code
https://github.com/Nhukangasniemi/Burger-Builder-App

Somehow, it works for some components to import css modules but for some components, it doesn't work. I'm using create-react-app, "typescript-plugin-css-modules": "^2.1.2"

**Comment by jsphstls** [comment]
I was dealing with a similar issue. My mistake was trying to set this up while combining CSS modules and Typescript for the first time. I also wrongly thought that this plugin was necessary for that to work.

Despite having the correct CRA version my CSS modules could not be found unless I added the `d.ts` file as suggested [here](https://github.com/mrmckeb/typescript-plugin-css-modules#custom-definitions).

My specific problem was having the auto-generated `react-app-env.d.ts` file in `/src` while my `compilerOptions` used `"include": ["src/lib" ]`. The definitions for CSS modules were never "included" so this plugin could not work as designed.

**Comment by mrmckeb** [comment]
Thanks for sharing @jsphstls!
