### ISSUE TITLE
@import not working with .css files

### ISSUE THREAD

**Issue by kirillvy** [mrmckeb/typescript-plugin-css-modules#75]
**Describe the bug**
An import of desktop.module.css, which itself has the line `@import './styles.module.css';` which contains a class called `.selector` only outputs the following definition: 

```
(alias) const styles: {
    'desktop': string;
}
```

instead of 

```
(alias) const styles: {
    'desktop': string;
    'selector': string;
}
```

**To Reproduce**

I reproduced the error [here](https://github.com/kirillvy/tcpm-error)

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/33430552/74521051-cd02fd00-4f29-11ea-9008-305c3fc57374.png)

MacOSX Catalina, VS Code  1.42.0
Typescript 3.7.5
typescript-plugin-css-modules 2.1.2

**Comment by mrmckeb** [comment]
Hi @kirillvy, this does seem like a bug... it's not something we've ever tested for I think.

Would you like to raise a PR and try to fix this? If not, I can take a look this weekend.

**Comment by mrmckeb** [comment]
Hi @kirillvy, sorry for the very slow reply.

This needs to be provided by the user, via a PostCSS config. You can see how we set that in our tests here - we use `postcss-import-sync2`.
https://github.com/mrmckeb/typescript-plugin-css-modules/blob/develop/src/helpers/__tests__/getDtsSnapshot.test.ts#L34

You can see how to set options here:
https://github.com/mrmckeb/typescript-plugin-css-modules#postcssoptions

Adding that config/plugin should solve your issues :) If not, please reopen this issue.
