### ISSUE TITLE
Not work with less and webpack when I choose webpack resolvers in less-loader

### ISSUE THREAD

**Issue by dancon** [mrmckeb/typescript-plugin-css-modules#77]
----------- Update 2020-03-16 -----------
I have fixed the issue by writing a [`less-plugin-aliases`](https://www.npmjs.com/package/less-plugin-aliases) that work with `typescript-plugin-css-modules` `customRenderer`, you just modify the config as below:

```json5
"compilerOptions": {
    "plugins": [
      {
        "name": "typescript-plugin-css-modules",
        "options": {
          // ...
          "customRenderer": "node_modules/less-plugin-aliases/lib/customRender.js"
        }
      }
    ],
    // ....
   "paths": {
        // config the paths
   }
}
```
You can use the `less-plugin-aliases` now, it works well in my project.

The plugin will read the `tsconfig.json` default to get the compilerOptions to resolve the `@import ~xx` case, and I also commit a [PR](https://github.com/mrmckeb/typescript-plugin-css-modules/pull/80) that inject the compilerOptions into `customRenderer` from ts plugin (I think this way is more elegant and power more to customRenderer ), after that the less plugin will not read `tsconfig.json` anymore.

--------------------------------------------------------------------------------

**Is your feature request related to a problem? Please describe.**

As [less-loader](https://github.com/webpack-contrib/less-loader#imports) says, I can choose webpack resovler by prepending my `@import` path with `~`, then the plugin does not work as expected.  

**Describe the solution you'd like**

In less file:
```
@import '~styles/variables.less';

// some code
```

In tsconfig.json

```
{
    "compilerOptions": {
         ...
         "paths":  {
              "styles/*": [path to styles folder]
         }
         ...
   }
}
```

In webpack.config file I also defined resolver.alias 

```
"styles": path to styles folder
```

Maybe when the plugin detect a @import path start begin `~`, deal it with `paths` defined in tsconfig.json

**Describe alternatives you've considered**

Now, I just use relative path to make it work, but it's ugly and nonportable.

**Additional context**

**Comment by mrmckeb** [comment]
Hi @dancon, thanks for reporting this.

Can you please provide a small reproduction? I will then take a look and try to resolve this by the end of the weekend!

**Comment by mfpopa** [comment]
Firstly, thanks @mrmckeb for creating and maintaining this. It is a much better solution than the plugins/loaders/solutions that create `.d.ts` files next to each CSS/SCSS file.

Secondly, I have the same problem I think. I have looked at the #26 #54 which looked like they were supposed to solve my problem, but they don't, unless I am doing something wrong.

Below is my config. Note that `./client` is the folder where I have all my client-side source code for this particular project.

```json
// tsconfig.json
...
"baseUrl": ".",
"paths": {
  "@client/*": ["client/*"]
}
...
```
```js
// webpack.config.js
...
alias: {
  '@client': path.resolve(__dirname, 'client'),
},
...
```
```tsx
// FormComponent.tsx
import { Button } from '@client/components/Button';
import styles from './FormComponent.module.scss';
...
<div className={styles.form} {...otherProps}>...</div>
...
```
```scss
// FormComponent.module.scss
@import '@client/styles/variables.scss';
...
.form {
  font-size: 14px;
}
...
```

Because I used the `@client` alias to import inside the SCSS file, now the `className={styles.form}` show a squiggly line under the word `form` and I get this error: `Property 'form' does not exist on type '{}'.ts(2339)`. If I use the relative import instead (`@import '../../styles/variables.scss';`) the plugin works fine. 

Webpack bundles everything properly and no complaints from VS Code and TypeScript for using the `@client` alias when importing in either TS/TSX files or SCSS files. The only thing that does not work with the alias is this plugin, `typescript-plugin-css-modules`.

Looking at the TS server log in VS Code, the plugin fails with:

```log
Info 84   [17:47:0.941] [typescript-plugin-css-modules] Failed Error: Can't find stylesheet to import.
  ╷
1 │ @import '@client/styles/variables.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  stdin 1:9  root stylesheet
Info 85   [17:47:0.954] [typescript-plugin-css-modules] Stack trace: Error: Can't find stylesheet to import.
  ╷
1 │ @import '@client/styles/variables.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  stdin 1:9  root stylesheet
    at Object._newRenderError (...\node_modules\sass\sass.dart.js:13621:19)
    at Object._wrapException (...\node_modules\sass\sass.dart.js:13467:16)
    at StaticClosure._renderSync (...\node_modules\sass\sass.dart.js:13442:18)
    at Object.Primitives_applyFunction (...\node_modules\sass\sass.dart.js:1064:30)
    at Object.Function_apply (...\node_modules\sass\sass.dart.js:4898:16)
    at _callDartFunctionFast (...\node_modules\sass\sass.dart.js:6580:16)
    at Object.renderSync (...\node_modules\sass\sass.dart.js:6558:18)
    at Object.exports.getClasses (...\node_modules\typescript-plugin-css-modules\lib\helpers\getClasses.js:75:18)
    at ...
```

Any help would be appreciated. Meanwhile, I will try to troubleshoot the plugin as much as I can. Is there a way to execute `node --inspect` on the plugin to debug it?

**Comment by dancon** [comment]
@mrmckeb  I'm so sorry for replying late, here is the [reproduction repo](https://github.com/dancon/ts-plugin-css-module), thank you for your greate job !

**Comment by mrmckeb** [comment]
Thanks @mfpopa.

Hi @dancon, this is not supported by Less natively, it's a feature of the loader. So the only way to make this work is to manually normalise the path based on the TS paths or something similar.

Would you like to try implementing that? If not, I can try over the weekend.

**Comment by dancon** [comment]
@mrmckeb  Yes, I know  why it doesn't work, and I'd love to fix it, but maybe by this weekend.

**Comment by dancon** [comment]
@mrmckeb Hi,   I'm trying to add the feature support by writing a less plugin, please note that ~

**Comment by kozlovvski** [comment]
+1, this feature would be also awesome in sass/scss. I use CRA with `sass-loader` and `baseUrl: "src/"` in `tsconfig.json`, so later I can import variables in any scss file like this: 

```scss
@import "~styles/variables" // assuming, that there is a file "src/styles/_variables.scss"
```
 By the way, thanks for this great package, it really makes me not pull out hairs from my head while working. It would be nice to see this kind of feature implemented in Typescript by default in the future.

**Comment by mrmckeb** [comment]
I'll release this today, thanks!

**Comment by mrmckeb** [comment]
This has been released, sorry for the long delay.
