### ISSUE TITLE
Classnames support

### ISSUE THREAD

**Issue by la99er** [mrmckeb/typescript-plugin-css-modules#81]
**Describe the solution you'd like**
I really like your plugin! It's awesome. I just had the issue, that I'm using `classnames` in combination with the `classnames-loader` within webpack. Thus I can do something like this in my component files:
```
import styles from './styles.scss'

<MyComponent className={styles('myStyle', {someOtherStyle: true})}
```
For more details, see: https://github.com/itsmepetrov/classnames-loader and https://github.com/JedWatson/classnames
So currently, I just get the error message: `This expression is not callable. Type '{ ... }' has no call signatures.`
Is there any chance that this can be supported somehow by your plugin?

**Comment by mrmckeb** [comment]
Hello @la99er, I definitely know that package - it's very cool. 

This is interesting, I've never used the Webpack loader... but I see the issue. 

We introduced a feature recently where you could provide your own template to solve problems like this. https://github.com/mrmckeb/typescript-plugin-css-modules#customtemplate

I can help you do that if you create a small repro-repo for me to play with. Or, alternatively I'd welcome a PR (again, happy to pair on that).

**Comment by la99er** [comment]
Thanks for the response! Yes I saw the option with the custom template and thought about that too. 
Sounds interesting to me! Never contributed to an open source project, so maybe I'll check if I can make a PR for that this weekend :)

**Comment by mrmckeb** [comment]
@la99er let me know if you're still interested in picking this up - if not, I'll close off.

Don't worry, I know life gets in the way sometimes, so no pressure!

**Comment by la99er** [comment]
I'm still interested in this feature, but I had some problems at the beginning with understanding how typescript plugins work. Then I somehow forgot about this issue and since then I use `// @ts-ginore` which really doesn't make me happy at all :D  
I'm not sure if I find time for implementing this feature and get my head into typescript plugin implementation. But when I have time for it, I'll try to do it :)

**Comment by mrmckeb** [comment]
No problem! I'll leave this open for now ;)

**Comment by mrmckeb** [comment]
I'm going to close this off for now, but if anyone wants to pick this up in future, feel free to open new issue.
