### ISSUE TITLE
Need advice. Doesn't work with ts-node

### ISSUE THREAD

**Issue by max-mykhailenko** [mrmckeb/typescript-plugin-css-modules#84]
**Describe the bug**
Problem is when I tried to compile application for my node I want to use same CSS modules as I'll use in the browser, but on compile stage I got an error 
```
> ts-node ./build/web/ssr.tsx
..../js/components/select-search/select-search.module.css:1
.select-search {
^

SyntaxError: Unexpected token '.'
```

**To Reproduce**
Try to run your ts file with import with ts-node.

**Expected behavior**
Got the same css classes in via tsc

**Comment by mrmckeb** [comment]
Hi @max-mykhailenko, this plugin can only help IDEs understand CSS imports. TypeScript doesn't allow plugins to transform code at this stage... although there are open issues about that.

To use CSS modules in Node for SSR, you'll need to use a Babel plugin for CSS modules or Webpack to process the CSS file. There are some articles on Medium that detail how to do this, like [this one](https://codeburst.io/react-server-side-rendering-ssr-with-express-and-css-modules-722ef0cc8fa0) (the first that came up).

Sorry we couldn't help you further! We certainly want to be able to transform code, but that's just not possible today.

**Comment by max-mykhailenko** [comment]
@mrmckeb thank you for your fast response, for me it was not so obviously (from babel perspective). Maybe you know how I can ignore css import with typescript (ts-node)? Want to just skip that import, but can't.

**Comment by mrmckeb** [comment]
Hi @max-mykhailenko, I think you'll definitely need to use either Babel or Webpack here - I don't think you'll be able to do this with Node in any other way.

You can use Babel with Node (without `ts-node`) as an alternative way to run your project, and then add a Babel plugin for CSS modules. This works well, I've done it before.

You could also look at something like Next.js which will do this for you (back and front-end config).
