### ISSUE TITLE
Import with query

### ISSUE THREAD

**Issue by yepninja** [mrmckeb/typescript-plugin-css-modules#89]
**Is your feature request related to a problem? Please describe.**
Can imoprt css with query:
```ts
import styles from './index.css?module'
```

**Describe the solution you'd like**
Ignore query in import

**Describe alternatives you've considered**
`customMatcher` option is not enough. Typescript can't resolve file with query

**Comment by mrmckeb** [comment]
Hi @yepninja, this is not something we've tested for - we try to cover the most common methods of working with CSS modules, and this is not an approach I've come across before.

As far as I can tell, TypeScript won't resolve this file as it strictly looks for a that has the extension `.css?module`. We don't currently modify how TypeScript loads files, only how it processes them.

My best advice at this stage is use a different approach:
- './index.m.css'
- './index.module.css'

However, we're always open to a PR if you'd like to take a look at adding support for this yourself :)

**Comment by yepninja** [comment]
Unfortunately you are right. Typescript doesn't support module resolver.

It's related to https://github.com/microsoft/TypeScript/issues/18896 and https://github.com/microsoft/TypeScript/issues/38094

**Comment by mrmckeb** [comment]
OK, I'll close this off for now - but feel free to repoen/raise this again if things change :) Sorry you hit this, I wish there was a simple solution.
