### ISSUE TITLE
[Less]: Fail when importing styles from node_modules

### ISSUE THREAD

**Issue by irrvrsl** [mrmckeb/typescript-plugin-css-modules#92]
**Describe the bug**
Plugin fails when I'm trying to import `.less` styles from `node_modules` both with relative and absolute paths. 

**To Reproduce**

1. Create `style.module.less` file
2. Import style from `node_modules`
3. Make `import style from './style.module.less'` in component
3. See error `Property 'container' does not exist on type '{}'`

**Expected behavior**
Imported .less module should include classNames

**Screenshots**
`tsconfig.json`

![image](https://user-images.githubusercontent.com/10095366/85826041-8f4e9480-b7a5-11ea-931e-7604c8c74760.png)

`data-table.module.less`

![image](https://user-images.githubusercontent.com/10095366/85826224-fcfac080-b7a5-11ea-92e3-b32d6b121450.png)

`data-table.tsx`

![image](https://user-images.githubusercontent.com/10095366/85826179-e2284c00-b7a5-11ea-8c33-326e51b7aee7.png)

**Desktop (please complete the following information):**

- OS: [MacOS 10.15.4]
- Browser [Safari]
- Version [13.1]

**Additional context**
For relative paths within `src` folder plugin works perfectly.

**Comment by KostkaBrukowa** [comment]
Hello, I have the same problem and I'm also using `AntD` library

**Comment by mrmckeb** [comment]
Hi there,

Unfortunately this is actually a feature of Webpack/the loader, and not Less - which is why it doesn't work automatically.

To help with this, we allow for custom renderers or to pass options through to Less (if that helps).
https://github.com/mrmckeb/typescript-plugin-css-modules#customrenderer

We recently had a contribution that added support for this custom renderer - which should solve the problem you're having:
https://github.com/dancon/less-plugin-aliases

Can you give it a go and let me know if it does? Thanks!

**Comment by KostkaBrukowa** [comment]
I've tried it with a lot of different configurations and still couldn't make it work. 
As far as I know plugin `less-plugin-aliases` just allows using `~` in import statement and replaces it with different directory. But without this plugin this snippet: 
```less
@import '../../node_modules/antd/lib/style/themes/default.less`
```
should work, but it doesn't for me.

**Comment by mrmckeb** [comment]
Hi @KostkaBrukowa, I think it would only work if that file wasn't also using `~` imports - can you confirm that it isn't?

**Comment by KostkaBrukowa** [comment]
I think there is no `~` imports in the file i'm importing. If you want to see for yourself I'm importing this file https://github.com/ant-design/ant-design/blob/master/components/style/dark.less and it's only importing from relative paths. I would also want to mention that by simply importing this file error occurs i don't even need to use any of the variables defined in the imported file.

**Comment by irrvrsl** [comment]
@mrmckeb Even with `less-plugin-aliases` same behavoir

This is what I found at `tsserver.log`, maybe it will be helpful

```[typescript-plugin-css-modules] Failed FileError: '~antd/lib/style/themes/default.less' wasn't found. 
Tried - PATH_TO_PROJECT/src/ui/templates/~antd/lib/style/themes/default.less,
npm://~antd/lib/style/themes/default.less,
~antd/lib/style/themes/default.less 
in PATH_TO_PROJECT/src/ui/templates/center-content.module.less on line 1, column 1:
1 @import '~antd/lib/style/themes/default.less';
```



![image](https://user-images.githubusercontent.com/10095366/86256378-15ba0a80-bbda-11ea-8543-45695c0cfad7.png)
![image](https://user-images.githubusercontent.com/10095366/86256398-1bafeb80-bbda-11ea-95c7-47ae39e481ac.png)
![image](https://user-images.githubusercontent.com/10095366/86256439-24a0bd00-bbda-11ea-8f81-b459c13cd79f.png)

**Comment by KostkaBrukowa** [comment]
I guess that it is something with the antd less file that I'm importing, because i've created the file `test.less` in the same directory that `theme.less` is and importing works fine despite being in `node_modules` folder

**Comment by mrmckeb** [comment]
Thanks for that info @KostkaBrukowa and @irrvrsl.  I haven't worked with Less for a while, but I'm assuming this has something to do with the aliases Ant Design are using inside of their project...

Hi @dancon, maybe you have some thoughts on this?

Again, the _root_ cause of this is that the aliases themselves aren't actually supported by Less directly, which is what this project relies on. 

Another option might be to try adding something like this into this project... 
https://www.npmjs.com/package/less-import-aliases

**Comment by irrvrsl** [comment]
Hello, @mrmckeb @KostkaBrukowa! I've got this thing work! After digging in `tsserver.log` I've found next error `[typescript-plugin-css-modules] Failed SyntaxError: Inline JavaScript is not enabled. Is it set in your options?`. So I set that option to `typescript-plugin-css-modules`:

```
{
  "name": "typescript-plugin-css-modules",
   "options": {
      "rendererOptions": {
         "less": {
           "javascriptEnabled": true
          }
       }
   }
}
```

@KostkaBrukowa please try this and give feedback

**Comment by KostkaBrukowa** [comment]
Hi @irrvrsl. Holy moly it works perfectly! Thanks you guys very much.

**Comment by irrvrsl** [comment]
Glad to hear that, I'm closing this issue. @mrmckeb thank you for this plugin and help👍

**Comment by mrmckeb** [comment]
Great news, thanks for the investigation!

**Comment by atzcl** [comment]
@irrvrsl @KostkaBrukowa refer to this pr to make `less-plugin-aliases` work normally
