### ISSUE TITLE
What i am doing wrong?

### ISSUE THREAD

**Issue by krutoo** [mrmckeb/typescript-plugin-css-modules#94]
Hi, i trying to use this plugin but i have some problems.

In my React project with **js/ts/jsx/tsx** files bundled by `webpack` with `ts-loader` i have error message in typescript log (in VS Code) and i do not have autocomplete for `scss` module default import properties.

I have installed plugin like this:
```bash
yarn add -D typescript-plugin-css-modules
```

my `tsconfig.json` looks like this:
```json
{
  "compilerOptions": {
      "outDir": "./build",
      "allowJs": true,
      "jsx": "react",
      "module": "commonjs",
      "target": "es6",
      "esModuleInterop": true,
      "plugins": [
        {
          "name": "typescript-plugin-css-modules",
          "options": {
            "customMatcher": "\\.scss$"
          }
        }
      ]
  },
  "include": [
      "./src/**/*",
      "module.d.ts"
  ]
}
```

I added `module.d.ts` file to root directory of my project with this content:
```typescript
declare module '*.scss' {
  const classes: { [key: string]: string };
  export default classes;
}
```

But in `tsx` popup with info about imported classes looks like this:
![image](https://user-images.githubusercontent.com/13140130/87848726-4c8f6080-c8fc-11ea-8853-27e08b07dfd7.png)

In **TS Server Log** in VS Code i have this error:
```
Info 27   [13:26:55.840] Failed to load module 'typescript-plugin-css-modules' from /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/node_modules: Error: Could not resolve JS module 'typescript-plugin-css-modules' starting at '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/node_modules'. Looked in: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript-plugin-css-modules/package.json...
```

in my project i have these dev dependencies:
```json
"ts-loader": "^8.0.1",
"typescript": "^3.9.7",
"typescript-plugin-css-modules": "^2.4.0",
```

what am I doing wrong?

**Comment by mrmckeb** [comment]
Hi @krutoo, the error indicates that it's trying to load the plugin from `/node_modules/node_modules`, and not relative to your project.

To check, have you set your workspace version of TypeScript as detailed here?
https://github.com/mrmckeb/typescript-plugin-css-modules#recommended-usage

**Comment by krutoo** [comment]
@mrmckeb In `.vscode/settings.json` i have this config:
```json
{
  "typescript.tsdk": "./node_modules/typescript/lib"
}
```

But i dont have command **TypeScript: Select TypeScript Version**

**Comment by krutoo** [comment]
it looks like the option is just not being output in command palette when file is not have `.js/.ts` extension, 
i found its option and its fully worked for me

i think issue can be closed

**Comment by mrmckeb** [comment]
Thanks for the update @krutoo!

**Comment by PindaPixel** [comment]
To add to this, I had the same issue as described here. I had a configuration issue in my vscode settings, `"typescript.tsdk"` was set to `"node_modules\\typescript\\lib"` rather than `"./node_modules/typescript/lib"` which fixed the loading issue for me. Additionally, installing from npm with -D did not install dev dependencies for this package, --save-dev did.

**Comment by JonathanLorimer** [comment]
I am getting this error as well. The paths that `typescript-plugin-css-modules` are trying to resolve are a bit strange:
```
Info 155  [11:37:59.105] Enabling plugin typescript-plugin-css-modules from candidate paths: /Users/jonathanlorimer/Mercury/mercury-web/node_modules/typescript/lib/tsserver.js/../../..,/Users/jonathanlorimer/Mercury/mercury-web/typescript-plugin-css-modules,/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features,/Users/jonathanlorimer/.vscode/extensions/jpoissonnier.vscode-styled-components-0.0.29,/Users/jonathanlorimer/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.2.3
```

I have this in a `.vscode/settings.json` file:
```
{
  "typescript.tsdk": "node_modules/typescript/lib"
}
```
but it still isn't resolving correctly. Is there anyway I can just point the plugin at my node_modules folder manually?

**Comment by mrmckeb** [comment]
Thanks @PindaPixel, I assume you're on Windows and not using WSL? That would make sense.

@JonathanLorimer that error indicates that your path is wrong for the plugin, perhaps... can you share a reproduction and raise a new issue? I can then investigate.

Sorry for the long delay in replying, I've been away.

**Comment by JonathanLorimer** [comment]
@mrmckeb I am not sure if this helps, commenting for posterity, or anyone else who comes across this issue.

Upgrading the library, deleting node_modules, re-installing, re-starting vscode seemed to fix this issue!

Thank you.

**Comment by mrmckeb** [comment]
Thanks for sharing!

**Comment by bonham000** [comment]
I ran into a similar issue where the plugin was working and then suddenly stopped working. Nothing I tried fixed it until I re-installed node modules `rm -rf node_modules && yarn`.
