### ISSUE TITLE
Lots of errors produced in WebStorm IDE with this plugin

### ISSUE THREAD

**Issue by ekilah** [mrmckeb/typescript-plugin-css-modules#97]
**Describe the bug**
When including this plugin in my `tsconfig.json`, the Intellij WebStorm IDE reports hundreds of errors that look like this:
```Error:(54, 33) TS1155: 'const' declarations must be initialized.```
![image](https://user-images.githubusercontent.com/3213339/88964049-a299c780-d25d-11ea-944e-c3e0228e2686.png)

When I remove this plugin, these errors go away.

**To Reproduce**
Use WebStorm in a project with this plugin. My `tsconfig` using ts `3.9.5`:
```
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "baseUrl": ".",
    "rootDir": ".",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "paths": {
      "~/*": ["src/*"]
    },
    "importsNotUsedAsValues": "preserve",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "isolatedModules": true,
    "plugins": [
      {
        "name": "typescript-plugin-css-modules",
        "options": {
          "customMatcher": "\\.css$"
        }
      }
    ]
  },
  "exclude": [
    "./node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "src/setupTests.ts"
  ]
}

```

The TypeScript window in the IDE will call the TS service and find errors for you.

**Expected behavior**
These errors wouldn't show up.

**Screenshots**
see above.

another very simple example:

![image](https://user-images.githubusercontent.com/3213339/88964701-96fad080-d25e-11ea-8af4-926f425332c5.png)
![image](https://user-images.githubusercontent.com/3213339/88964798-bdb90700-d25e-11ea-9305-ce9654ebdccf.png)

**Desktop (please complete the following information):**

- OS: Mac OSX Catalina

**Additional context**
We use CSS modules and some PostCSS features, though these errors seem to pop up in files that don't do anything fancy like PostCSS's nesting, too.

**Comment by mrmckeb** [comment]
I was just thinking about wha could cause this and it might be to do with this:
https://github.com/mrmckeb/typescript-plugin-css-modules/blob/f9af73d1abe2bb3bca01310eb659c942bea9fbfb/src/helpers/createExports.ts#L42-L44

It seems to be only occurring in IntelliJ editors, so it might be to do with the way they use (or don't use) the TypeScript Language Service. 

As a quick test, could you edit the source code, so that it declares with `let` instead?

**Comment by ekilah** [comment]
@mrmckeb Sorry it took so long to try this out, been busy!

Yes, that change does seem to fix the issue! It's annoying to test because it seems like I have to quit/restart Webstorm for it to decide to consume the changes in my `package.json` 😛 , but I confirmed the hundreds of errors disappeared with this change.

Added that to a PR: https://github.com/mrmckeb/typescript-plugin-css-modules/pull/100

**Comment by mrmckeb** [comment]
Thanks @ekilah, I've replied to the PR.

**Comment by ekilah** [comment]
Hm, I tried the beta today and I get the same errors. I realize the reason the errors were gone when using my patch was probably because I was using the following in `package.json`: `"typescript-plugin-css-modules": "https://github.com/ekilah/typescript-plugin-css-modules#patch-2",`

That doesn't get 'built', so the directory in `node_modules` only has TS files. Maybe this was just preventing the editor from running the plugin at all, and it was failing silently.

I changed `package.json` from `prepublishOnly` to `prepare` as suggested by https://stackoverflow.com/questions/40528053/npm-install-and-build-of-forked-github-repo and installed my patch again, and was able to see errors still. So, I guess there is another issue causing this.

**Comment by mrmckeb** [comment]
You can also install _locally_ by using something like `yarn add file:../../path/to/module` and it works. Or you can try Yarn/npm link.

I assume you're right, it wasn't running at all.

What is the error you're seeing now @ekilah?

**Comment by ekilah** [comment]
The same error as the original post, with or without my patch and with or without your beta, unfortunately

**Comment by mrmckeb** [comment]
Hi @ekilah, there was another place where const was used. Can you try `2.6.0-beta.1` and let me know if that works for you?

**Comment by ekilah** [comment]
Sure, will do tomorrow.

**Comment by ChristopherHaws** [comment]
Just as an FYI, I am also having this issue in Visual Studio 2019.
![image](https://user-images.githubusercontent.com/5934505/93389831-983d8800-f821-11ea-9d28-d362da272272.png)

**Comment by ChristopherHaws** [comment]
After updating to the latest beta, the 'const' errors did go away, but they were replaced with:
![image](https://user-images.githubusercontent.com/5934505/93394197-acd14e80-f828-11ea-8942-92dbbcf48cb3.png)

**Comment by ekilah** [comment]
Same here. Glad to hear this is reproducible in a more-widely available IDE!

**Comment by mrmckeb** [comment]
Thanks for that.

Can you please try `v2.7.0`? I think it will solve the issue finally... I hope so!

**Comment by ekilah** [comment]
![image](https://user-images.githubusercontent.com/3213339/93619847-ff784b00-f98d-11ea-8685-99474442b5f5.png)

Seems to work great now in WebStorm. I will say, the editor did seem to take a while to load up the TS service when I added the plugin back in, I wonder how heavy this is.

Also the `readonly`s in the error message are a bit distracting, since they are repeated a lot. Was that a "just for correctness" piece or does it actually do something important? (idk how the internals of the plugin work)

**Comment by ChristopherHaws** [comment]
@mrmckeb That fixed it for me in VS 2019. Everything seems to be working now! 👍

**Comment by mrmckeb** [comment]
@ekilah this seems to be an issue with the CSS now, which is good news. It means that `button` wasn't found in that file... can you share a very small reproduction of the issue?

Thanks for the feedback @ChristopherHaws!

**Comment by ekilah** [comment]
@mrmckeb there is no issue. I was just showing it working.

**Comment by mrmckeb** [comment]
Thanks for the update!
