### ISSUE TITLE
Consider TS path aliases for Sass

### ISSUE THREAD

**Issue by jens-duttke** [mrmckeb/typescript-plugin-css-modules#98]
In my `tsconfig.json` I have aliases for specific paths:

```json
{
	"compilerOptions": {
		"paths": {
			"@ui": ["ts/ui"],
			"@utils": ["ts/utils"],

			"@fonts/*": ["fonts/*"],
			"@img/*": ["img/*"],
			"@json/*": ["json/*"],
			"@scss/*": ["scss/*"]
		},
```

In my WebPack configuration I'm using the same configuration to make Webpack and it's plugins aware of these aliases.

Unfortunately, if I have an `@import` on such an alias, the `typescript-plugin-css-module` fails to get the class names.

e.g. a styles.module.scss:
```
@import "@scss/_custom-media.scss";

.dialog {
	width: 500px;
}
```
In that case, it does not resolve the alias for "@scss/_custom-media.scss" and the whole module is empty, instead of containing `dialog`.

TypeScript itself is able to resolve "@scss", so I wonder if it's possible using this plugin to use such aliases too.

**Comment by mrmckeb** [comment]
Hi @jens-duttke, I think we could add support for this. Would you be interested in raising a PR for it?

**Comment by bluef1ash** [comment]
Hi @mrmckeb, can you support this feature as soon as possible? So much needed!

**Comment by mrmckeb** [comment]
Hi @bluef1ash, I'm 100% in favour of supporting this - but I don't personally have the time to add this feature in right now. If someone can pick this up and create a PR, I would be happy to help get it out quickly :)
